### ISSUE TITLE
the error messages of running demo_toy_problem.ipynb

### ISSUE THREAD

**Issue by wenouyang** [jakeret/tf_unet#1]
Hi Jakeret,

When running demo_toy_problem.ipynb, executing this line of code `path = trainer.train(generator, "./unet_trained", training_iters=20, epochs=100, display_step=2)` . I got the following error messages, do you mind sharing any insights on what causes the problem

Verification error= 16.7%, loss= 0.8326                                             
Start optimization                                                                  
Traceback (most recent call last):                                                  
  File "/test/tfw/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 480, in _process_fetches                                                                                                                     
    allow_operation=True)                                                                                                  
  File "/test/tfw/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 2301, in as_graph_element                                                                                                                     
    % (type(obj).__name__, types_str))                                                                                     
TypeError: Can not convert a list into a Tensor or Operation.                                                              

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 30, in <module>
    path = trainer.train(generator, "./unet_trained", training_iters=20, epochs=100, display_step=2)
  File "/home/user/test/u-net/ver3/unet.py", line 364, in train                                     
    self.net.keep_prob: dropout})
  File "/test/tfw/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/test/tfw/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 523, in _run
    processed_fetches = self._process_fetches(fetches)
  File "/test/tfw/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 493, in _process_fetches
    % (subfetch, fetch, type(subfetch), str(e)))
TypeError: Fetch argument [<tf.Tensor 'gradients/Conv2D_grad/Conv2DBackpropFilter:0' shape=(3, 3, 1, 16) dtype=float32>, <tf.Tensor 'gradients/Conv2D_1_grad/Conv2DBackpropFilter:0' shape=(3, 3, 16, 16) dtype=float32>, <tf.Tensor 'gradients/Conv2D_2_grad/Conv2DBackpropFilter:0' shape=(3, 3, 16, 32) dtype=float32>, <tf.Tensor 'gradients/Conv2D_3_grad/Conv2DBackpropFilter:0' shape=(3, 3, 32, 32) dtype=float32>, <tf.Tensor 'gradients/Conv2D_4_grad/Conv2DBackpropFilter:0' shape=(3, 3, 32, 64) dtype=float32>, <tf.Tensor 'gradients/Conv2D_5_grad/Conv2DBackpropFilter:0' shape=(3, 3, 64, 64) dtype=float32>, <tf.Tensor 'gradients/Conv2D_6_grad/Conv2DBackpropFilter:0' shape=(3, 3, 64, 32) dtype=float32>, <tf.Tensor 'gradients/Conv2D_7_grad/Conv2DBackpropFilter:0' shape=(3, 3, 32, 32) dtype=float32>, <tf.Tensor 'gradients/Conv2D_8_grad/Conv2DBackpropFilter:0' shape=(3, 3, 32, 16) dtype=float32>, <tf.Tensor 'gradients/Conv2D_9_grad/Conv2DBackpropFilter:0' shape=(3, 3, 16, 16) dtype=float32>, <tf.Tensor 'gradients/add_grad/Reshape_1:0' shape=(16,) dtype=float32>, <tf.Tensor 'gradients/add_1_grad/Reshape_1:0' shape=(16,) dtype=float32>, <tf.Tensor 'gradients/add_2_grad/Reshape_1:0' shape=(32,) dtype=float32>, <tf.Tensor 'gradients/add_3_grad/Reshape_1:0' shape=(32,) dtype=float32>, <tf.Tensor 'gradients/add_4_grad/Reshape_1:0' shape=(64,) dtype=float32>, <tf.Tensor 'gradients/add_5_grad/Reshape_1:0' shape=(64,) dtype=float32>, <tf.Tensor 'gradients/add_7_grad/Reshape_1:0' shape=(32,) dtype=float32>, <tf.Tensor 'gradients/add_8_grad/Reshape_1:0' shape=(32,) dtype=float32>, <tf.Tensor 'gradients/add_10_grad/Reshape_1:0' shape=(16,) dtype=float32>, <tf.Tensor 'gradients/add_11_grad/Reshape_1:0' shape=(16,) dtype=float32>] of [<tf.Tensor 'gradients/Conv2D_grad/Conv2DBackpropFilter:0' shape=(3, 3, 1, 16) dtype=float32>, <tf.Tensor 'gradients/Conv2D_1_grad/Conv2DBackpropFilter:0' shape=(3, 3, 16, 16) dtype=float32>, <tf.Tensor 'gradients/Conv2D_2_grad/Conv2DBackpropFilter:0' shape=(3, 3, 16, 32) dtype=float32>, <tf.Tensor 'gradients/Conv2D_3_grad/Conv2DBackpropFilter:0' shape=(3, 3, 32, 32) dtype=float32>, <tf.Tensor 'gradients/Conv2D_4_grad/Conv2DBackpropFilter:0' shape=(3, 3, 32, 64) dtype=float32>, <tf.Tensor 'gradients/Conv2D_5_grad/Conv2DBackpropFilter:0' shape=(3, 3, 64, 64) dtype=float32>, <tf.Tensor 'gradients/Conv2D_6_grad/Conv2DBackpropFilter:0' shape=(3, 3, 64, 32) dtype=float32>, <tf.Tensor 'gradients/Conv2D_7_grad/Conv2DBackpropFilter:0' shape=(3, 3, 32, 32) dtype=float32>, <tf.Tensor 'gradients/Conv2D_8_grad/Conv2DBackpropFilter:0' shape=(3, 3, 32, 16) dtype=float32>, <tf.Tensor 'gradients/Conv2D_9_grad/Conv2DBackpropFilter:0' shape=(3, 3, 16, 16) dtype=float32>, <tf.Tensor 'gradients/add_grad/Reshape_1:0' shape=(16,) dtype=float32>, <tf.Tensor 'gradients/add_1_grad/Reshape_1:0' shape=(16,) dtype=float32>, <tf.Tensor 'gradients/add_2_grad/Reshape_1:0' shape=(32,) dtype=float32>, <tf.Tensor 'gradients/add_3_grad/Reshape_1:0' shape=(32,) dtype=float32>, <tf.Tensor 'gradients/add_4_grad/Reshape_1:0' shape=(64,) dtype=float32>, <tf.Tensor 'gradients/add_5_grad/Reshape_1:0' shape=(64,) dtype=float32>, <tf.Tensor 'gradients/add_7_grad/Reshape_1:0' shape=(32,) dtype=float32>, <tf.Tensor 'gradients/add_8_grad/Reshape_1:0' shape=(32,) dtype=float32>, <tf.Tensor 'gradients/add_10_grad/Reshape_1:0' shape=(16,) dtype=float32>, <tf.Tensor 'gradients/add_11_grad/Reshape_1:0' shape=(16,) dtype=float32>] has invalid type <class 'list'>, must be a string or Tensor. (Can not convert a list into a Tensor or Operation.)

**Comment by jakeret** [comment]
Weird! This seems to be caused somewhere deep in Tensorflow. What version are you using?

The code works fine on my MacBook Pro, Tensorflow '0.10.0rc0' and Python '3.4.4'

**Comment by wenouyang** [comment]
Hi Jakeret, this is the version information I am using:

python -c 'import tensorflow as tf; print(tf.__version__)'
0.8.0

import sys
print(sys.version)
3.4.4 (default, May 19 2016, 07:45:08)
[GCC 5.3.0]

**Comment by wenouyang** [comment]
Hi Jacket, it looks to me that this line of code `gradients = sess.run((self.optimizer, self.net.cost, self.learning_rate_node, self.net.gradients_node), feed_dict={self.net.x: batch_x,self.net.y: util.crop_to_shape(batch_y,pred_shape), self.net.keep_prob: dropout})` does not work for the version before 0.10. I changed it to `_,loss,lr,gradients = sess.run([self.optimizer, self.net.cost, self.learning_rate_node]+self.net.gradients_node,feed_dict={self.net.x: batch_x,self.net.y: util.crop_to_shape(batch_y, pred_shape),self.net.keep_prob: dropout})
`, but it right now gives the error message such as `ValueError: too many values to unpack (expected 4)
`

Just curious, are there any approaches to solve this problem without upgrading to the version you are using. Thank you very much.

**Comment by jakeret** [comment]
Sorry I'm traveling at the moment. However, I don't have any experience
with Tensorflow < 0.9.0. So I don't know if it's runnable with your version

**Comment by wenouyang** [comment]
Thank you, with some help, I got this figured out.
