### ISSUE TITLE
How to compute f1 score

### ISSUE THREAD

**Issue by lowkeygit** [jakeret/tf_unet#100]
I implemented the U-net and then got a satisfied result. However, I don't know how to compute the f1 score. For example, based on the toy_problem, how to compute the f1 score in this problem? I don't know how to get the y_pred and y_true.
Hope anyone can give me some advices.

Thanks a lot.

**Comment by jakeret** [comment]
I usually use `scikit-learn` for that. To get prediction you can use the `predict` method of the model

**Comment by reshu-b7** [comment]
Hi,

I'm trying to implement the same and want to plot the ROC curve of the results. How can we do it here ?

Thanks.

**Comment by jakeret** [comment]
For binary classification problems this can also easily be done with scikit-learn
