### ISSUE TITLE
Linear slowdown with the number of epochs

### ISSUE THREAD

**Issue by Snubben-B** [jakeret/tf_unet#102]
I'm running the 'launcher.py' script that is included with rectangles=False. Nothing has been modified. I am experiencing a quite severe linear slowdown with the number of epochs (see graphs), with the last epoch taking about 3.6 times as much time as the first one. What causes this and is it expected behavior?
![slowdown](https://user-images.githubusercontent.com/31923965/30482334-e04400e4-9a22-11e7-9838-1e6bcd302aa9.png)

**Comment by jakeret** [comment]
Interesting, I never noticed this behaviour before (which doesn't mean it didn't happen) and I also don't really have an explanation for this. Any chance that you could analyze which bit is taking more and more time? Are you running on CPU or GPU?

**Comment by Snubben-B** [comment]
I'm using a GPU. I will try to do some profiling.

**Comment by jakeret** [comment]
Great, highly appreciated

**Comment by Snubben-B** [comment]
The problem seems to be in the following lines:

if avg_gradients is None:
    avg_gradients = [np.zeros_like(gradient) for gradient in gradients]
for i in range(len(gradients)):
    avg_gradients[i] = (avg_gradients[i] * (1.0 - (1.0 / (step+1)))) + (gradients[i] / (step+1))
end = time.time()

epoch 0      epoch 99
0.0089s  ->  0.0259s

------------

self.norm_gradients_node.assign(norm_gradients).eval()

epoch 0      epoch 99
0.8883s  ->  11.53s

------------

save_path = self.net.save(sess, save_path)

epoch 0      epoch 99
2.1133s  ->  23.2779s

They all appear to increase linearly with epochs.

**Comment by jakeret** [comment]
Hmm very interesting insights. The normalized gradients could probably be computed in a more efficient way to mitigate the large computational cost. (Or be drop completly)
What puzzles me more is the increasing saving time. Is the size of the checkpoint also growing over time?

**Comment by Snubben-B** [comment]
model.cpkt.meta is growing. As I understand it this file should store the graph structure, so I don't see why it would be growing.

**Comment by jakeret** [comment]
If added a parameter that disables the default computation of the normalized gradients. That should prevent the slowdown

**Comment by ceps1986** [comment]
Hi Joel, 

Great stuff! I just ran into this same issue. I noticed that the norm_gradients are not fed back to the network. Is this correct? Where you calculating these just to keep track of them?
