### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by fischersci** [jakeret/tf_unet#104]
The size of my input images is 3400x1600, I am using the U-net-code unchanged and would like to train the network
I am running the code on my GPU, a Titan X with 12GB memory, but have to limit the features on 8 and use a batch size of 1, otherwise I would get an "OOM" error.
Is this usual that so much memory is required, because I think 12 GB on the GPU is not tot bad? I also read in the u-net paper that there is the "tiling strategy" applied in order to analyse images of any size, is this strategy applied in the tf_unet code too?
Is someone is familiar with these issues, I would be glad about any help.

**Comment by jakeret** [comment]
The networks tend to use a lot of memory especially if you use a deep one. Also, in the original paper they use an input of size 576x576.  Probably you should resize your input a bit

**Comment by fischersci** [comment]
Thanks, I will follow this advice. 
Furthermore is the "tiling strategy" which is mentioned in the U-Net paper applied in this code, too?

**Comment by jakeret** [comment]
This is not done automatically.

**Comment by valentin-krasontovitsch** [comment]
Just stumbled upon this - so if you had a (small) number of bigger images, let's say with relatively samll objects you're trying to segment, and many of those, would it make sense to preprocess the images to create tiles and feed that into the network?
does one only solve hardware constraints with that? or might the performance of the network be affected (positively) as well? If i understand coorectly, the latter should not be the case, as it's a convolutional net, and you have convolutions, and pooling, and so on...
