### ISSUE TITLE
Very large Output image

### ISSUE THREAD

**Issue by Fab1900** [jakeret/tf_unet#105]
My prediction size is (5, 676, 288, 2), and by using img = to_rgb(pred[..., 1].reshape(-1, ny, 1)) my output image has the size (3380, 288, 3) but i should be (676, 288, 3). I know the issue must be the batch size >1 but what can I do to overcome this problem?

**Comment by jakeret** [comment]
This output usually comes in handy to track and visualize the overall learning process. Considering this I'm not quite sure what the problem should be

**Comment by Fab1900** [comment]
Oh yes you are right, thanks!
