### ISSUE TITLE
Learning on multiple classes

### ISSUE THREAD

**Issue by peterrot** [jakeret/tf_unet#107]
First of all thanks for providing this implementation!
My question: I want to classify among 4 different classes, so I prepared dataset where each image has 4 different colors on it (each color corresponds to a class).
What would be the easiest way to try tf_unet on such dataset (in ImageDataProvider it's hardcoded for 2 classes)? Or do you maybe have an example/demo to deal with more than 2 classes?
Thanks in advance

**Comment by jakeret** [comment]
You can change the number of classes in the ImageDataProvider after having created an instance. Anyhow, I don't think that this will do the trick in your case.
One way to go is to use the [`SimpleDataProvider`](https://tf-unet.readthedocs.io/en/latest/tf_unet.html#tf_unet.image_util.SimpleDataProvider). Where you build your own loading mechanism first and feed in the data as a Numpy array.
