### ISSUE TITLE
Missing training files

### ISSUE THREAD

**Issue by ubersexualShupeng** [jakeret/tf_unet#108]
Dear Author,

I successfully downloaded & installed the tf_unet following the "Tensorflow Unet Documentation Release 0.1.0". However, I found the training files are missing when I input the code (from the documentation page 3, bottom): 
data_provider = image_util.ImageDataProvider("fishes\train\*.tif") 

The error message shows: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\windows\system32\tf_unet\tf_unet\image_util.py", line 166, in __init__
    assert len(self.data_files) > 0, "No training files"
AssertionError: No training files

I wondering if I can download the train files from other places? Can you provide the link to download these training files?  
Thank you.

-Shupeng

**Comment by jakeret** [comment]
hi ubersexual 🥇 
The package doesn't ship with train files. The example is only to get the idea across. 

If you want to run the code have a look at the [demo](https://github.com/jakeret/tf_unet/tree/master/demo) and scripts

**Comment by ubersexualShupeng** [comment]
Thank you Jakeret. It is an excellent demo. I learn a lot from it.

**Comment by riazalis** [comment]
Dear Author,

I have installed this package ("tf_unet") and can run the demo (toy) example. Now, I want to train and test it with my images dataset but I don't know how to do this. 

Can you kindly tell how can I train it with my images? (I mean, where should I put images folder? Should I follow certain folder names conventions like "training" and "validation" or "masks" etc.?)

Thanking in anticipation.

**Comment by jakeret** [comment]
The [`ImageDataProvider`](http://tf-unet.readthedocs.io/en/latest/tf_unet.html#tf_unet.image_util.ImageDataProvider) expects a `glob` path pointing to your files. Additionally you can pass `data_suffix` and `mask_suffix`. The default there is `.tif`. So you would have to change it to `.png`

**Comment by riazalis** [comment]
Thanks for your reply.

Now, that error is removed, but when I run the code, I got the following error:

    File "C:\Python\Python35\site-packages\tf_unet-0.1.1-py3.5.egg\tf_unet\image_util.py", line 98, in __call__
    X[i] = train_data

    ValueError: could not broadcast input array from shape (1760,2049,3) into shape (1753,2046,3)

I thought that might be because of different resolutions of images, so I resized all the images with the same resolution. Then I got the following error:

    ValueError: could not broadcast input array from shape (1753,2046,4) into shape (1753,2046)

What could be the reason behind this error?

Thanks.

**Comment by jakeret** [comment]
The code actually looks fine. Just wondering if this is correct `"/image_files/*.tif"`. Are your files really in the system root directory?

**Comment by azizmrr** [comment]
hey Joel, I got that fixed. Now, I have  a new error "could not broadcast input array from shape (3032,1438,3) into shape (2990,1455,3)" on line 98 image_util.py  X[i] = train_data. how to fix this?

**Comment by jakeret** [comment]
Just a wild guess. There is a known bug if the number of pixels in x or y is not even

**Comment by azizmrr** [comment]
so I tried resizing the images to even number of pixels and still get the same error.

**Comment by jakeret** [comment]
have you checked the values of `data_provider.n_class` and `data_provider.channels`? Does it correspond to your dataset?

**Comment by azizmrr** [comment]
> have you checked the values of `data_provider.n_class` and `data_provider.channels`? Does it correspond to your dataset?
do you mean the data generated by your example? How do I check that?
