### ISSUE TITLE
training result of bmmc dataset

### ISSUE THREAD

**Issue by gopi77** [jakeret/tf_unet#109]
Hi

I trained the bmmc dataset from https://lmb.informatik.uni-freiburg.de/resources/datasets/tem.en.html.
But the results are not good. Attached the ipynb file as html for reference.
[u-net_bmmc.html.zip](https://github.com/jakeret/tf_unet/files/1327233/u-net_bmmc.html.zip)

Please guide me to get better results.

Note:
I renamed the segmented files as "_mask.tif" & kept on the folder named "train"

The datasets inside the "train" folder look like
BMMC_1.tif
BMMC_1_mask.tif
BMMC_2.tif
BMMC_2_mask.tif
...
...
Total of 43 pair (tif & mask)
and for test I kept only one tif & mask file.

Regards
Gopi. J

**Comment by jakeret** [comment]
I would suggest you experiment with different network architecture. Considering you small data set, have a look at data augmentation and normalization.
