### ISSUE TITLE
About the gradients saved

### ISSUE THREAD

**Issue by NanPhi** [jakeret/tf_unet#110]
in the line 482-488 of unet
```
def _update_avg_gradients(avg_gradients, gradients, step):
    if avg_gradients is None:
        avg_gradients = [np.zeros_like(gradient) for gradient in gradients]
    for i in range(len(gradients)):
        avg_gradients[i] = (avg_gradients[i] * (1.0 - (1.0 / (step+1)))) + (gradients[i] / (step+1))
        
return avg_gradients
```
I am kind of confused about the gradients calculation here, may you please give me a short explanation why you set gradients like this?

**Comment by jakeret** [comment]
This is mainly for debugging purpose. This computes the average gradients and visualizes it in tensorboard. If I looks odd then it might be an indication that something is not quite right with the training

**Comment by NanPhi** [comment]
thanks, now I see
