### ISSUE TITLE
Custom Data Set, Color Images, 3 classification 

### ISSUE THREAD

**Issue by brappazzo** [jakeret/tf_unet#111]
Hello I am trying to use unet on a custom data set of colored images that have the standard 3 RGB channels. My question is how would I configure the mask for each image given that there are three different classifications I want? 
I guess to clarify should the mask just be an image file with 3 channels and the mask be indicated by a value of 1 in one of the channels for each image (the rest being 0) ?

**Comment by jakeret** [comment]
The easiest would be to use the [`SimpleDataProvider`](http://tf-unet.readthedocs.io/en/latest/tf_unet.html#tf_unet.image_util.SimpleDataProvider)

Then you have to pass the mask as `[n, X, Y, classes] ` binary numpy array

**Comment by brappazzo** [comment]
Okay thank you for the response. But does this mean that all the data and labels have to be loaded in memory as np arrays then?

**Comment by jakeret** [comment]
This is the simplest approach. If you want to avoid that, have a look at this class http://tf-unet.readthedocs.io/en/latest/tf_unet.html#tf_unet.image_util.BaseDataProvider
