### ISSUE TITLE
RFI and star data

### ISSUE THREAD

**Issue by kaushiksk** [jakeret/tf_unet#113]
Really grateful for your work!
I was wondering if there's a proper documentation on the pipeline to generate the RFI data. I understand I am to use HIDE & SEEK, but is there a small tutorial that helps to understand how to set up the pipeline?

Also is the stars and galaxies data open sourced? I would like to reproduce these results.

Regards

**Comment by kaushiksk** [comment]
Also, in the RFI example, `seek --file-prefix='./bgs_example_data' --post-processing-prefix='bgs_example_data/seek_cache' --chi-1=20 --overwrite=True seek.config.process_survey_fft` processes only one file. How do I change the flags to run it on all the files in the folder?

**Comment by jakeret** [comment]
The example BGS data was actually recorded with a telescope and only one day has been made publicly available. 
To generate simulated data you can indeed use the HIDE package (see the [usage section](http://hide.readthedocs.io/en/latest/usage.html)). SEEK should in principle automatically process all the data available. Maybe you have to adapt the start and end date (`strategy_start` `strategy_end` in `seek.config.process_survey_fft`

**Comment by kaushiksk** [comment]
There are a lot of h5 available now in the provided link. And when I ran
the command you provided it only processed the first file. I will look into
it anyway.

Regards,
Kaushik S Kalmady

**Comment by kaushiksk** [comment]
Regarding the RFI demo, shouldn't the prediction be a binary image? Why is it outputting something similar to the input itself?
How can I check how good the predictions are? Because I clearly can't compare it with the ground truth. I have trained it for 55 epoch and it still outputs the color map.

**Comment by jakeret** [comment]
> There are a lot of h5 available now in the provided link. 

Each file represents 15 minutes worth of data. After the SEEK processing all files are merged into one representing the entire day

> Regarding the RFI demo, shouldn't the prediction be a binary image?

I don't think so. The output of `tf_unet` is the probability for each pixel that it contains RFI or not.

> Because I clearly can't compare it with the ground truth. 

The output of SEEK contains a RFI mask computed with a different algorithm, which represents something like the ground thruth.

This being said, using only the data publicly available (1 day) it is very unlikely to train a good model. In the paper we used months worth of data.
