### ISSUE TITLE
3D UNet

### ISSUE THREAD

**Issue by leacornelio** [jakeret/tf_unet#114]
is there any way to convert this UNet implementation to 3D?

**Comment by jakeret** [comment]
You probably have to change the shape of the input and output tensors and
replace the 2D operations with the 3D counterpart. But it's hard to say if
this is sufficient

**Comment by leacornelio** [comment]
Is it possible to use conv3d to process 2d images?

**Comment by jakeret** [comment]
I don't have any experience with conv3d. You have to try
