### ISSUE TITLE
Is it possible to train on GPU using this implementation?

### ISSUE THREAD

**Issue by dimaxano** [jakeret/tf_unet#115]

**Comment by jakeret** [comment]
Yes, it's based on tensorflow. If you follow their install instruction it
will run on the GPU out of the box

**Comment by dimaxano** [comment]
Hm, I've installed tensorflow-gpu using pip. 
Should I make TF for gpu from sources instead?

**Comment by AlibekJ** [comment]
Would suggest going with standard Tensorflow tutorials first to make sure
gpu is working.

**Comment by mas-dse-greina** [comment]
Just to verify. If you run the demo programs (e.g. toy) on a GPU-enabled tensorflow installation then it should use the GPU by default. Is that correct? No other settings to change in the program?

Thanks.

**Comment by dimaxano** [comment]
@mas-dse-greina Yes, you are right.
