### ISSUE TITLE
Problems with starting tensorboard

### ISSUE THREAD

**Issue by fischersci** [jakeret/tf_unet#116]
When I start tensorboard in the command, the window is frozen like it is loading. The problem is that it doesn't continue anymore. I was even waiting a day. I am calling it the common way: "tensorboard --logdir=path
 Can someone help me please?

**Comment by jakeret** [comment]
Not sure if this is unet related. Have you tried a different browser?

**Comment by fischersci** [comment]
I am just calling it via cmd

**Comment by fischersci** [comment]
OK, I get a link now, but nothing is visualized due to no event files are found or they are empty.  Actually there is only one event file and I have to state the path to the folder in which this event file is located when I am calling tensorboard, am I right?

**Comment by jakeret** [comment]
Yes excatly

**Comment by fischersci** [comment]
Ok but then I do not understand why it does not work...

**Comment by fischersci** [comment]
The event file has a size of 700.000 KB, could that be a problem?

**Comment by jakeret** [comment]
Have you tried to open smaller files? Do you get the same issue?

**Comment by fischersci** [comment]
It works now, I am just calling it now from H: instead of C:
