### ISSUE TITLE
In scripts.radio_util Dataprovider what does the first positional argument "nx" do?

### ISSUE THREAD

**Issue by kaushiksk** [jakeret/tf_unet#117]
In the RFI demo problem you have used two different positional arguments from training and testing(600 and 10000). I visualised the data obtained through both dataproviders 
[Images](https://imgur.com/a/D7vns)

I have very little experience with RFI and am curious to know what the difference primarily is. I understand that we are seeing a different "slice" of the data, but this slice is respect to which axis? What exactly is the change we are observing?

**Comment by jakeret** [comment]
What you see is a spectrogram (fft of radio data). Hence, the x-axis is representing time and the y-axis frequencies
