### ISSUE TITLE
All pixels predicted as 0.5

### ISSUE THREAD

**Issue by Incurablex** [jakeret/tf_unet#119]
Hi Jakeret,

I am using your package for image segmentation, and it worked like a charm! The only issue I had is that sometimes the output (prediction values) are all 0.5. I have run a few tests and found that even if I train two models with the same image sets and the same configuration, the prediction from one model for a test image is good, but the prediction from the other model on the same test image may give all 0.5. Do you have any idea what the reason could be? Thanks!

**Comment by jakeret** [comment]
Great to hear that the package is useful to you.

Unfortunately, I don't have an explanation for this behaviour. There is a known issue with the pixelwise softwaremax that may lead to some training issue depending on the values of the gradients

**Comment by Incurablex** [comment]
Jakeret,

Thanks! I think I figured out. It was due to the zero values around my image boundaries.

**Comment by jakeret** [comment]
Great!

**Comment by TonyChouZJU** [comment]
Almost the same problem. I trained a 2-class model.  For the background pixel (labeled in 0) , the prediction is ok. But for the foreground pixel, the prediction is 0.5 for label 0 and 0.5 for label 1.

![CEB23F6A-C6AE-42c0-A8E0-53CA3215776F](https://user-images.githubusercontent.com/7860865/58240631-f8333400-7d7d-11e9-8632-092f0f8aabd6.png)
