### ISSUE TITLE
Inference speed decrease

### ISSUE THREAD

**Issue by fischersci** [jakeret/tf_unet#125]
Hey,
When I using interference in order to predict the images with my trained net, I noticed that the process is becoming more and more slowly. 
Is someone aware of this issue?

**Comment by jakeret** [comment]
How is it slowing down? Over the course of multiple prediction? How do you benchmark the time?

**Comment by fischersci** [comment]
Yes I have a for loop which is 360 times executed inorder to predict 360 images (see attached screenshot). I just check the time when prediction images are created. First there are only few seconds between created images, but at number 200 it already takes about 20 minutes sometimes.

**Comment by fischersci** [comment]
![inferenz](https://user-images.githubusercontent.com/32009628/32372101-c1866240-c093-11e7-9334-e9da2b40f47d.png)

**Comment by jakeret** [comment]
Wondering if this is related to this issue #102 .
Do you have [that version](https://github.com/jakeret/tf_unet/blob/master/tf_unet/unet.py#L299) of the code

**Comment by fischersci** [comment]
No I haven't, but can this be the issue although when inference is used no average gradient is computed?

**Comment by jakeret** [comment]
Yes you're absolutely right. My bad. 
Which line is taking more an more time?
What I noticed is that the session is reinitialized in every iteration (twice: in `net.predict` and on line 63). In principle this cold be avoided on only be done one before the loop
