### ISSUE TITLE
Transposed convolution versus UpSampling

### ISSUE THREAD

**Issue by mas-dse-greina** [jakeret/tf_unet#126]
I've seen two versions of the up-pooling operation used by UNet. In some Keras models they use UpSampling2D which I think is calling tf.NearestNeighbors.  In tf_unet it looks like Transposed Convolution is being used. I know there is a difference between the two approaches. I'm wondering what the advantages/disadvantages are to using either? Is one faster? Does one give more accurate predictions?

**Comment by jakeret** [comment]
I haven't used `tf.NearestNeighbors` so I can't provide any kind of explaination
