### ISSUE TITLE
Reading excessive image data

### ISSUE THREAD

**Issue by nikkou** [jakeret/tf_unet#127]
Suppose I have a folder with *_train.png, *_mask.png and other unrelated files, then current ImageDataProvider will treat these unrelated files as training data. It happens because ImageDataProvider._find_data_files() returns all files except for mask files.

I would rewrite this to ignore all files except for those that have data_suffix or mask_suffix.

**Comment by jakeret** [comment]
You can either subclass the `ImageDataProvider` and provider your own implementation of `_find_data_files` or you find a [search pattern](https://github.com/jakeret/tf_unet/blob/master/tf_unet/image_util.py#L142) that excludes the unwanted files

**Comment by nikkou** [comment]
Yes, but is the default implementation correct? 

Maybe `[name for name in all_files if self.data_suffix in name and not self.mask_suffix in name]` would be more appropriate, because otherwise some files without data_suffix can be read and then, for example, `replace(self.data_suffix, self.mask_suffix)` fails in _next_data().

**Comment by jakeret** [comment]
Good point, makes sense. Could you send me a Pull Request for this?

**Comment by nikkou** [comment]
Pull request #128 merged.
