### ISSUE TITLE
Object has no attribute 'shape'

### ISSUE THREAD

**Issue by MatthiasUni-Mainz** [jakeret/tf_unet#135]
Hey,
i am very new to unet and i am having some troubles.
Here is my code:
data_provider = image_util.ImageDataProvider('UltraschallDone/*',data_suffix='.png',mask_suffix='_1.png')
data_provider.n_class = 3

net = unet.Unet(layers=3, features_root =32, channels = 3, n_class = 3)

trainer = unet.Trainer(net,batch_size=5,norm_grads=True,optimizer="adam")
path = trainer.train(data_provider,output_path="D:/UltraschallDone",training_iters=1,epochs =1)

prediction = net.predict("D:/UltraschallDone/model.cpkt",data_provider)

When i am running the project, i get the following Error:
INFO:tensorflow:Restoring parameters from D:/UltraschallDone/model.cpkt
2017-12-11 12:00:49,386 Restoring parameters from D:/UltraschallDone/model.cpkt
2017-12-11 12:00:49,682 Model restored from file: D:/UltraschallDone/model.cpkt
Traceback (most recent call last):
  File "D:/Pycharm/tf_unet/testNet.py", line 13, in <module>
    prediction = net.predict("D:/UltraschallDone/model.cpkt",data_provider)
  File "D:\Pycharm\tf_unet\unet.py", line 266, in predict
    y_dummy = np.empty((x_test.shape[0], x_test.shape[1], x_test.shape[2], self.n_class))
AttributeError: 'ImageDataProvider' object has no attribute 'shape'

I don' know why it happens to be honest (just to get the error message, i made 1 training iteration with 1 echo)
I am using Tensorflow Version 1.4 on a i7--4770 CPU @3.4 GHz, 16GB Ram and Windows 10.
Hopefully we can fix this and maybe i made just a small mistake.

**Comment by jakeret** [comment]
It seems like that in `net.predict("D:/UltraschallDone/model.cpkt",data_provider)`  you are passing an instance of the `data_provider`. 
If you look at the [documentation](http://tf-unet.readthedocs.io/en/latest/tf_unet.html#tf_unet.unet.Unet.predict), you should pass the data that you want to run the prediction on.

**Comment by MatthiasUni-Mainz** [comment]
Right, should have figured it out by myself :/, but i guess it somehow slipped of my view.

Sorry to bother you again, but i have like 2 more questions to ask, more or less on my own problem i want to train with unet.

First my dataset contains ultrasound images of different image sizes ( i am looking at muscle ultrasound). Since the paper only used pictures of the same size, i couldnt find the specific points where i have to adapt the code in the proper way. Is there a way to do so?

Second you use Lables for your ground truth in form of black and white, but is there a way to change that to 3 coloured Label-images ( for my specific problem it is necessary to have those 3 colours)

**Comment by jakeret** [comment]
No worries. 

Have a look at the [`ImageDataProvider`](https://github.com/jakeret/tf_unet/blob/master/tf_unet/image_util.py#L177). There you can hook in to resize all your input to the same size.
To code is in principle capable to cope with multiclass input as well. See the docs for more infos
