### ISSUE TITLE
Manunal prediction without Data_Provider

### ISSUE THREAD

**Issue by fschi** [jakeret/tf_unet#136]
Hello,
first thanks sharing your code - it's really helpful! 

I managed to train the network and the predictions are good. But now, when I want to use the network without your Data_Provider (something like: _prediction = net.predict("Path-to-CPKT", testImg)_ ) I get a strange result:

With this Code:
`
           path ='/home/sf/UNet/tf_unet/data/temp/0177_1_1.jpg'
          
           #manual loading
           testImg = np.array(Image.open(path), np.float32)
           testImg = np.expand_dims(testImg, axis=0)
           prediction = net.predict("./unet_trained/model.cpkt", testImg)
           mask = prediction[0,...,1] > 0.9

           #using Data_Provider
           x_test, y_test = data_provider(1)
           predictionDataProvider = net.predict("./unet_trained/model.cpkt", x_test)
           maskDP = predictionDataProvider[0,...,1] > 0.9

           fig, ax = plt.subplots(1, 3, sharex=True, sharey=True, figsize=(12,5))

           ax[1].imshow(maskDP, aspect="auto")
           ax[2].imshow(mask, aspect="auto")
           ax[0].set_title("---")
           ax[1].set_title("Data Provider")
           ax[2].set_title("manual Prediction")
           fig.tight_layout()
           fig.savefig(f)
`
I just get this strange predictions like on the right side. The prediction on the left is from the same Image, but using the Data_Provider.

![outputerror](https://user-images.githubusercontent.com/32751220/33930993-03826f98-dfef-11e7-82e7-efaf44e1b0bb.png)

Any Idea why the prediction on the right seems so 'broken'?

Thanks for your help!

**Comment by jakeret** [comment]
Wild guessing: The `data_provider` normalizes the values to (0,1]. Is this maybe something you have to do as well when manually loading the data?

**Comment by fschi** [comment]
Thanks a lot! Solved the problem..
