### ISSUE TITLE
How to get multiple images as output?

### ISSUE THREAD

**Issue by monicakapadia** [jakeret/tf_unet#139]
Hi, 
    Your code is very helpful for me. But the problem is it take only first image from the dataset as a input and give single image as output.
    Actually, I am begginer in the tensorflow. So, can you please give me suggestion how to get multiple images as output?

Here is my code:
#preparing data loading
data_provider = ImageDataProvider("C:/Users/path/*.png")

#setup & training
net = unet.Unet(channels=1, n_class=2, layers=3, features_root=16)
trainer = unet.Trainer(net)
path = trainer.train(data_provider, output_path, training_iters=10, epochs=4)

x_test, y_test = data_provider(4)
prediction = net.predict(path, x_test)

fig, ax = plt.subplots(1,3, figsize=(12,4))
ax[0].imshow(x_test[0,...,0], aspect="auto")
ax[1].imshow(y_test[0,...,1], aspect="auto")
ax[2].imshow(prediction[0,...,1], aspect="auto")

fig.tight_layout()
plt.show()

**Comment by jakeret** [comment]
Hi, great to hear that the code is useful to you. 
Not quite sure what is not working in you case. In principle your code

```
x_test, y_test = data_provider(4)
prediction = net.predict(path, x_test)
```

should return 4 predictions. Have you checked the shape of `prediction`?
Or is the plotting actually the issue?

**Comment by monicakapadia** [comment]
Hi, 
   It is not an issue with plotting and prediction shape is (3, 336, 460, 2). I think problem is with data_provider. In my code **data_provider** = ImageDataProvider("C:/Users/path/*.png")** I think it  take a one image.
  I also show your demo program of Radio Frequency Interference. In that it take one file.
![capture](https://user-images.githubusercontent.com/31838870/34429490-d9ea7bd4-ec7e-11e7-95f4-18bcaf6e136c.JPG)
Now, can please tell me that what should i do for taking multiple images ?.. Because i want to segment all imaeges which are in one folder.

**Comment by jakeret** [comment]
In the Radio Frequency demo I have only one file, so thats ok.

If the shape of `prediction` is `(3, 336, 460, 2)` then this mean you received 3 predictions from the unet.

**Comment by monicakapadia** [comment]
see sir, what i am trying to say is that, I want to take multiple images which are in same folder as well as same number of images i got from output.
 So, If i want to multiple images in your code than what should i do?

**Comment by jakeret** [comment]
I think you have to change the way you create the `ImagaDateProvider`:

`data_provider = ImageDataProvider("C:/Users/path/*", data_suffix=".png", mask_suffix='_mask.png')`

Have a look at the [documentation](https://tf-unet.readthedocs.io/en/latest/tf_unet.html#tf_unet.image_util.ImageDataProvider) for more details.

**Comment by monicakapadia** [comment]
Right, ok so if I try this :
```
data_provider = image_util.ImageDataProvider("C:/Users/Administrator/Desktop/dataset/singleimage/*.png", data_suffix=".png", mask_suffix='_mask.png')
net = unet.Unet(channels=1, n_class=2, layers=3, features_root=16)
trainer = unet.Trainer(net,optimizer="momentum", opt_kwargs=dict(momentum=0.2))
path = trainer.train(data_provider, output_path, training_iters=10, epochs=4)
x_test, y_test = data_provider(4)
prediction = net.predict(path, x_test)
```
Still i get single image as output...

**Comment by jakeret** [comment]
If you look at the [code](https://github.com/jakeret/tf_unet/blob/master/tf_unet/image_util.py#L173) you will see that the implementation is simply using `glob`. So you need to pass it an appropriate search pattern

**Comment by monicakapadia** [comment]
okay Got it!!! thank you @jakeret

**Comment by Billsbob** [comment]
We have similar issue with saving output images without overwriting them.  Is there a way to use util.save_image to loop through all data input files and save an individual output file for each?

Currently we have six new data inputs, but it only saves one output image, prediction.tiff

```
from tf_unet import image_util, unet, util
import glob

model_path = 'output/model.ckpt'
datapath = 'images/verification/*.tif'
files = glob.glob(datapath)

data_provider = image_util.ImageDataProvider(datapath, data_suffix = '.tif')
data_provider.channels = 1
net = unet.Unet(channels=1, n_class=2, layers=3, features_root=64)


data,label = data_provider(1)
prediction =net.predict(model_path, data)

unet.error_rate(prediction, util.crop_to_shape(label, prediction.shape))

img = util.combine_img_prediction(data, label, prediction)
util.save_image(img, "prediction/prediction.tif")
```
