### ISSUE TITLE
Training and testing guide

### ISSUE THREAD

**Issue by UCRajkumar** [jakeret/tf_unet#140]
Maybe I'm not seeing it, but it would be really helpful if the readme contained the following information.

1. How to train the network (i.e. which file to run, where the data folder is, etc)
2. How to test the trained network with an example image
3. And how to modify the hyper parameters. 
4. What format the data is.

**Comment by jakeret** [comment]
Admittedly, it's not in the readme but you can find the information in the documentation:
1. See the [usage section](http://tf-unet.readthedocs.io/en/latest/usage.html) of the rtd
2. There is an [executable demo](https://hub.mybinder.org/user/jakeret-tf_unet-jl6zym18/notebooks/demo/demo_toy_problem.ipynb) on binder
3. There are ample examples in the [script folder](https://github.com/jakeret/tf_unet/tree/master/scripts)
4. The unet uses simple [tensors as input](http://tf-unet.readthedocs.io/en/latest/tf_unet.html#tf_unet.unet.Unet)
