### ISSUE TITLE
image format 

### ISSUE THREAD

**Issue by myway0101** [jakeret/tf_unet#142]
Thank you again for this valuable implementation.

I have one simple question about image format for training.

In the usage of tutorial document: http://tf-unet.readthedocs.io/en/latest/usage.html

.TIF image format is used for data loading as shown in below:
#preparing data loading
data_provider = image_util.ImageDataProvider("fishes/train/*.tif")

I am wondering can I just use any image formats for example.BMP and .JPG by changing the corresponding data_suffix?

**Comment by jakeret** [comment]
The loading is based on the `Pillow` package. So anything that this package can handle is supported
