### ISSUE TITLE
dead link in demo/demo_radio_data.ipynb

### ISSUE THREAD

**Issue by CourseraSIA** [jakeret/tf_unet#143]
The data used in demo/demo_radio_data.ipynb, which should be found at:
http://people.phys.ethz.ch/~ast/cosmo/bgs_example_data/
is no longer available.

**Comment by jakeret** [comment]
Thanks for reporting this. I will try to put it back online asap

**Comment by MXtreme** [comment]
Any update about this?

**Comment by jakeret** [comment]
oh I forgot.. I'm on it now

**Comment by jakeret** [comment]
fixed
