### ISSUE TITLE
Trying to read image with 3 classes

### ISSUE THREAD

**Issue by UCRajkumar** [jakeret/tf_unet#145]
I have a training data with the following parameters: input image is rgb image of size 500x500. The ground truth has 3 classes with the following values for pixels: 0, 50, 100. I'm trying to read in this image as: `generator = image_util.ImageDataProvider("data/train/*.tif", n_class=3)`

However, I produce this error: 

> Traceback (most recent call last):
  File "meta_net.py", line 19, in <module>
    x_test, y_test = generator(1)
  File "/home/Desktop/Projects/tf_unet/tf_unet/image_util.py", line 88, in __call__
    train_data, labels = self._load_data_and_label()
  File "/home/Desktop/Projects/tf_unet/tf_unet/image_util.py", line 58, in _load_data_and_label
    return train_data.reshape(1, ny, nx, self.channels), labels.reshape(1, ny, nx, self.n_class),
ValueError: cannot reshape array of size 251001 into shape (1,501,501,3)

How do I properly read in images with multiple classes? I tried looking at ufig_util for some ideas, but I couldn't extract too much from that.

**Comment by jakeret** [comment]
The implementation is expecting that you have a one-hot encoding for the ground truth.

**Comment by b-z** [comment]
@jakeret 
Does it mean, I should put each label into an individual channel?
for example, 
> channel 1:
> [0, 0, 1, 0]
> channel 2:
> [0, 1, 0, 1]
> channel 3:
> [1, 0, 0, 0]

like this?

**Comment by jakeret** [comment]
> Does it mean, I should put each label into an individual channel?
Yes exactly

**Comment by UCRajkumar** [comment]
I understand this is probably a very noob question but how exactly is that done? A generic example would be very helpful. I don't quite understand what the purpose of the 4th element is for in each channel.

**Comment by UCRajkumar** [comment]
I found that this solution works for an arbitrary number of classes. Please consider incorporating this into your present code: 

`            nx = label.shape[1]
            ny = label.shape[0]
            labels = np.zeros((ny, nx, self.n_class), dtype=np.float32)
            labels[..., None] == np.unique(label).astype(int)
        return labels`

**Comment by UCRajkumar** [comment]
I am able to successfully read the image using this code: `nx = label.shape[1]
            ny = label.shape[0]
            labels = np.zeros((ny, nx, self.n_class), dtype=np.float32)
            labels[..., 2] = (label==200).astype(int)
            labels[..., 1] = (label==100).astype(int)
            labels[..., 0] = (label==0).astype(int)`

and I changed `label = self._load_file(label_name, np.bool)` to `label = self._load_file(label_name)` in next_data. When I print the images, everything checks out and I can see the two segmentation using `ax[1].imshow(y_test[0,...,1], aspect="auto")
ax[2].imshow(y_test[0,...,2], aspect="auto")`

as 
![capture](https://user-images.githubusercontent.com/9893724/34759334-ef69f27c-f58f-11e7-92a9-378300d688da.JPG)

But when I go to train the image: the 2nd label from the ground truth is missing as so: 
![capture](https://user-images.githubusercontent.com/9893724/34759379-253f0ba8-f590-11e7-946f-0e3f280fd296.JPG)

The left image is supposed to be the ground truth and the right image is the prediction. If you notice, in the ground truth, the segmentations for the 2nd label is missing. What am I doing wrong? 

I used the exact same configurations as the toy demo problem, the only difference is this line `generator = image_util.ImageDataProvider("data/train/*.tif", n_class=3)`

**Comment by jakeret** [comment]
I think this is just a[ plotting issue](https://github.com/jakeret/tf_unet/blob/master/tf_unet/util.py#L102).

**Comment by UCRajkumar** [comment]
I changed the util.py to plot both channels as you suggested using this line:

 `img = np.concatenate((to_rgb(crop_to_shape(data, pred.shape).reshape(-1, ny, ch)), 
                          to_rgb(crop_to_shape(gt[..., 1], pred.shape).reshape(-1, ny, 1)), 
                          to_rgb(crop_to_shape(gt[..., 2], pred.shape).reshape(-1, ny, 1)), 
                          to_rgb(pred[..., 1].reshape(-1, ny, 1)), to_rgb(pred[..., 2].reshape(-1, ny, 1))),axis=1)`

However, my predictions still look exactly the same. In this image, I've pasted the 2 classes of interest and their predictions. 
![capture](https://user-images.githubusercontent.com/9893724/34933582-3c997a54-f98c-11e7-97db-cfc8805d0e0d.JPG)



Is there nothing in unet.py that I should change? I'm suspecting that perhaps, in unet.py, there is some default setting that only trains it for the 2 classes case. So even if the 3rd class was provided, it doesn't read it?

**Comment by UCRajkumar** [comment]
Just for sanity sake, I ran a single training image for 50 epochs on a 3 layer, 32 root feature, netork and then ran that exact same image as the test image. During the entire training time, the accuracy stayed absolutely constant. Then, when I tested, it didn't perform well at all. If I'm training on just a single image then essentially, the network would pretty much memorize that one image and so, if I were to feed in that exact same image to the trained network, it should classify the classes pretty well shouldn't it? Or am I flawed in my thinking?

**Comment by jakeret** [comment]
I assume that you call the [constructor ](https://github.com/jakeret/tf_unet/blob/master/tf_unet/unet.py#L179)correctly.

It seems like the network is not learning. An indication for that is sometimes this odd grid on the prediction. 
As for the accuracy, it seems that your data is quite unbalanced so this might not be the best performance measure.
Have you experimented with larger networks?

**Comment by UCRajkumar** [comment]
I am calling the constructor as: 

`net = unet.Unet(channels=generator.channels, n_class=generator.n_class, layers=3, features_root=32)`

`generator.channels` and `generator.n_class` both output 3 (I verified with print statements). 

Sorry, I'm not too familiar with the jargon. What exactly do you mean by "odd grid on the prediction?"
Do you have suggestions for a better performance measure? 

Currently, my hardware doesn't have the processing power for larger networks. When I tried it with 5 layers, it hangs after a while. I will try to test it on capable hardware soon.

**Comment by jakeret** [comment]
This is not a particular deep learning jargon. This is just me trying to say that I see some sort of grid pattern on the prediction and this is what happens if the network doesn't learn.
The problem with accuracy and class inbalance is: if you have 99% class A and 1% class B and the network is always predicting class A, you have an accuracy of 99%. 

This being said, accuracy is the default in `tf_unet`. So don't get to hang up on that metric.

If you can't upscale the network, try to downscale the problem/images

**Comment by daboe01** [comment]
@jakeret does one-hot mean that the label-image needs to have red, green and blue pixels?

this does not seem to work.

<img width="1092" alt="Bildschirmfoto 2019-03-09 um 16 40 27" src="https://user-images.githubusercontent.com/146335/54073651-3c885b00-428a-11e9-8ec2-504df541b415.png">
the prediction is sort of empty:
<img width="1007" alt="Bildschirmfoto 2019-03-09 um 16 42 42" src="https://user-images.githubusercontent.com/146335/54073677-65a8eb80-428a-11e9-9944-50e7ed11e6e7.png">

**Comment by daboe01** [comment]
figured it out.
background must be blue, not black.
precisely one color for each class.
<img width="645" alt="Bildschirmfoto 2019-03-09 um 20 57 59" src="https://user-images.githubusercontent.com/146335/54076607-25f3fb00-42ae-11e9-9a4a-12e0bc4ef6b8.png">
