### ISSUE TITLE
objects visible in tensorboard, but not in the prediction

### ISSUE THREAD

**Issue by fschi** [jakeret/tf_unet#151]
Hello,
I have this phenomena, that when I monitor the Unet with tensorboard, I can see the structures I want to detect (see attached image). 
![images](https://user-images.githubusercontent.com/32751220/35337757-4df87722-011c-11e8-92f0-f32710f2f54a.png)

But the prediction covers just parts of this detected area (see example Input/Output). Whats my mistake or what should i change? It occurs after >100 epochs after it seems to be converged. The Unet has 2 layers and 128 Features.
![exampleinput](https://user-images.githubusercontent.com/32751220/35337714-31a16eee-011c-11e8-8853-38d95b9c27c8.jpg)
![exampleoutput](https://user-images.githubusercontent.com/32751220/35337715-31d0b56e-011c-11e8-99ca-4fd9ee41b59f.jpg)

Thanks for your help!

**Comment by jakeret** [comment]
Not sure if I understand the question correctly.

If the question is, why the output is smaller than the input then the answer is, that this is expected behaviour. The deeper the unet the worse it gets - there is a good explainination in the original Ronneberger et al paper.

A possible way to circumvent this, is to mirror the edges of your input images to make them "larger"

**Comment by fschi** [comment]
thanks for your answer but I did not mean that. 

The problem is, that the UNet seems to detect all the droplets i want to detect (at least all small and big droplets are visible in tensorboard during the training as visualized in the first image).
But in the prediction all the small droplets are missing and bigger ones are shown incomplete ( example in the last 2 images).

Do you have an idea how to improve the prediction quality?

**Comment by jakeret** [comment]
Ah I see, sorry for that.

How do the images look like that are spit out during the trainings phase? 
Do they look like the ones in Tensorboard or like the ones you get from the prediction?

**Comment by fschi** [comment]
No Problem! 
The images that are saved during training look like the ones from the prediction

**Comment by jakeret** [comment]
Ok, this might suggest that something is not quite right with the learning. What you see in tensorboard are intermediate representations which only tell a part of the story.

If I were you I would experiment with the network architecture a bit (maybe deeper with less features). Futhermore it might be beneficial to experiment with some preprocessing techinques.

**Comment by fschi** [comment]
thanks, I will try that
