### ISSUE TITLE
Multi-GPU training

### ISSUE THREAD

**Issue by kvrd18** [jakeret/tf_unet#17]
Have you guys figured out how to incorporate Multi-GPU training as explained in the Cifar-10 [tutorial](https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_multi_gpu_train.py)?

**Comment by jakeret** [comment]
I never really considered multi-gpu training, mainly because for my datasets the training completed within a few hours.
In principle this could be implemented by subclassing the Trainer-class and assignin one image per gpu in every iteration
