### ISSUE TITLE
something about test

### ISSUE THREAD

**Issue by zzt941006** [jakeret/tf_unet#178]
@jakeret 
I was trying to train the images using your codes. But the prediction values are strange.
I just want to distinguish bg and fg. However, for all the pixels, bg prob = nan, and fg prob = 0.0.
Even when I test it using training data, the result is still the same.
looking forward to your reply thks!

**Comment by jakeret** [comment]
Looks like the network is not learning anything. Have you checked that your `data_provider` is working correctly (data&labels format, correctly normalized, etc)?
