### ISSUE TITLE
Toy demo problem outputs black screen

### ISSUE THREAD

**Issue by wkeithvan** [jakeret/tf_unet#182]
The toy demo problem is currently outputting a black image.

![toy_problem](https://user-images.githubusercontent.com/6819623/40689592-1019606e-6360-11e8-8978-27503d30ef18.png)

I did a fresh git clone of the repository and ran the Jupyter Notebook from demos (I had to copy it into the root folder to get the `from tf_unet import ...`  lines working). Having made no other changes to any of the code, the image above is what I currently get at the last cell of the Jupyter Notebook. the last cells a few more time generates new images, but still gives a blank prediction.

**Comment by jakeret** [comment]
I also just ran a fresh copy and I'm getting the expected results. Are the intermediate results in the `prediction` folder also all black? Have you checked the tensorboard?

BTW: You don't need to copy the notebooks around if you install the package with: 
`python setup.py develop`

**Comment by wkeithvan** [comment]
I just recloned it again and ran it. No problems now. I was having trouble the same day on two separate computers, so possibly it is a dependencies issue I've since fixed on them in the days since.

One other question...
In `tf_unet/layers.py`, what is the point of `def weight_variable_devonc`? As far as I can tell, it is the same as `def weight_variable`...

**Comment by wkeithvan** [comment]
Also, I noticed that there is one fewer up convolution layers than down convolution layers (3 down, 2 up in the default configuration). According to the original U-Net paper, shouldn't the number of up convolutions match the number of down convolutions (3 each for the default configuration)?

**Comment by jakeret** [comment]
Ok good to know, glad it resolved.
This is mainly for historical reasons but in principle it would give you the option to have different intializations for the down und up convolutions.

There are many more (down) convolution layers as up convolutions, this is ok. However there are the same number of max pooling (down sampling) operations as up convolutions (up sampling)
