### ISSUE TITLE
toy problem

### ISSUE THREAD

**Issue by samsammurphy** [jakeret/tf_unet#192]
A friend and I both separately ran the toy problem (using default options) and got the same prediction error, i.e. an all black screen (prediction of no filled circles).

![toy_problem](https://user-images.githubusercontent.com/16657983/41842275-3c594a6a-7862-11e8-8784-0ef77ed25d60.png)

Seems odd that the toy problem does not work out of the box. This might be what #168 is referring to?

I will try increasing the `training_iters` and report back here..

**Comment by samsammurphy** [comment]
Increasing `training_iters` worked :tada: 

![toy_problem](https://user-images.githubusercontent.com/16657983/41845274-dbe48164-786a-11e8-97c4-c6f062073475.png)

I will open a simple PR to make a suggestion to increase it in the official demo..

**Comment by wkeithvan** [comment]
This looks the same to what I had in #182
