### ISSUE TITLE
Trainer would remove files in output_path if already exist

### ISSUE THREAD

**Issue by hsieh42** [jakeret/tf_unet#216]
Following the usage example in https://tf-unet.readthedocs.io/en/latest/usage.html, if the output_path is an existing path and contains files and directories, the line trainer.train(data_provider, output_path,...) would remove everything in output_path. This is very detrimental.

**Comment by jakeret** [comment]
At the moment this is done intentionally. One way around it is to pass different output_path per run.  The benefit of that is that it becomes easier to compare the runs in tensorboard
