### ISSUE TITLE
Typeerror in demo

### ISSUE THREAD

**Issue by hftsai** [jakeret/tf_unet#22]
Hi Jakeret,
I have been very interested in applying unet for my research. And it's been great to find out you already applied tensorflow with unet.
I've installed tensorflow on kubuntu linux. The version for tensorflow is 1.0.1 and Keras used by tensorflow is 1.2.2.

I wanted to try your demo_toy_problem.
however i expected typeerror problem during execution of the line net=unet.Unet

> --------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)
<ipython-input-7-778ffd89a317> in <module>()
----> 1 net = unet.Unet(channels=generator.channels, n_class=generator.n_class, layers=3, features_root=16)

/home/davince/lib/python2.7/site-packages/tf_unet-0.1.0-py2.7.egg/tf_unet/unet.pyc in __init__(self, channels, n_class, cost, cost_kwargs, **kwargs)
    187         self.keep_prob = tf.placeholder(tf.float32) #dropout (keep probability)
    188 
--> 189         logits, self.variables, self.offset = create_conv_net(self.x, self.keep_prob, channels, n_class, **kwargs)
    190 
    191         self.cost = self._get_cost(logits, cost, cost_kwargs)

/home/davince/lib/python2.7/site-packages/tf_unet-0.1.0-py2.7.egg/tf_unet/unet.pyc in create_conv_net(x, keep_prob, channels, n_class, layers, features_root, filter_size, pool_size, summaries)
    109         bd = bias_variable([features//2])
    110         h_deconv = tf.nn.relu(deconv2d(in_node, wd, pool_size) + bd)
--> 111         h_deconv_concat = crop_and_concat(dw_h_convs[layer], h_deconv)
    112         deconv[layer] = h_deconv_concat
    113 

/home/davince/lib/python2.7/site-packages/tf_unet-0.1.0-py2.7.egg/tf_unet/layers.pyc in crop_and_concat(x1, x2)
     52     size = [-1, x2_shape[1], x2_shape[2], -1]
     53     x1_crop = tf.slice(x1, offsets, size)
---> 54     return tf.concat(3, [x1_crop, x2])
     55 
     56 def pixel_wise_softmax(output_map):

/home/davince/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.pyc in concat(values, axis, name)
   1027       ops.convert_to_tensor(axis,
   1028                             name="concat_dim",
-> 1029                             dtype=dtypes.int32).get_shape(
   1030                             ).assert_is_compatible_with(tensor_shape.scalar())
   1031       return identity(values[0], name=scope)

/home/davince/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.pyc in convert_to_tensor(value, dtype, name, preferred_dtype)
    635       name=name,
    636       preferred_dtype=preferred_dtype,
--> 637       as_ref=False)
    638 
    639 

/home/davince/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.pyc in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype)
    700 
    701         if ret is None:
--> 702           ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    703 
    704         if ret is NotImplemented:

/home/davince/local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.pyc in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    108                                          as_ref=False):
    109   _ = as_ref
--> 110   return constant(v, dtype=dtype, name=name)
    111 
    112 

/home/davince/local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.pyc in constant(value, dtype, shape, name, verify_shape)
     97   tensor_value = attr_value_pb2.AttrValue()
     98   tensor_value.tensor.CopyFrom(
---> 99       tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
    100   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    101   const_tensor = g.create_op(

/home/davince/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.pyc in make_tensor_proto(values, dtype, shape, verify_shape)
    365       nparray = np.empty(shape, dtype=np_dt)
    366     else:
--> 367       _AssertCompatible(values, dtype)
    368       nparray = np.array(values, dtype=np_dt)
    369       # check to them.

/home/davince/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.pyc in _AssertCompatible(values, dtype)
    300     else:
    301       raise TypeError("Expected %s, got %s of type '%s' instead." %
--> 302                       (dtype.name, repr(mismatch), type(mismatch).__name__))
    303 
    304 

TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
>

I wonder if you know that could cause this problem? was it because my installation of a newer version of tensorflow?

thank you.
Best,

**Comment by jakeret** [comment]
Hi @hftsai great to hear that tf_unet is useful to you. Looks like that the API changed a bit from Tensorflow 0.12.0 (which I'm using) and the new Tensorflow 1.0. I haven't had the time to upgrade yet but there is a PR (#19) adressing this issue. You chould check it out to see if it solves your issue

**Comment by hftsai** [comment]
Dear Jakeret,
thank you.
I reverted back to 0.12 and seems to work out.
I'll learn on it and work on upgrading to tensorflow 1.0 which i think ameya005 has already started.

best,
