### ISSUE TITLE
Model saving not working

### ISSUE THREAD

**Issue by ameya005** [jakeret/tf_unet#23]
I am using Tensorflow 0.12 along with the latest master branch. I have trained the u-net for around a 1000 patches and the results from the prediction images are encouraging. But when I save the model and restore it in another session, the output is similar to that of a freshly initialized model. Please let me know if anybody has managed to run a save and restore operation and if any specific changes are needed.

**Comment by jakeret** [comment]
How are you restoring the model? Are you using something like this 
```prediction = net.predict(path, x_test)``` ?

I just checked with one of the examples in the `scripts` folder and it seemed to work as it should. I also tried to load the model from a new python interpreter and didn't see any issue.

**Comment by ameya005** [comment]
Hi, I was able to fix the issue. I had added a import_meta_graph in the prediction function to pick the graph. That was resetting the restored values to init. Thanks a lot for the help.
