### ISSUE TITLE
ValueError: could not broadcast input array from shape (300,300,2) into shape (300,300)

### ISSUE THREAD

**Issue by mfrohman123** [jakeret/tf_unet#238]
Hello,

Thank you for providing an implementation for this network! I am trying to train the network on 300*300 images with two classes. I understand your implementation expects one hot encoding images, which I believe I am doing so via:
```
def sample(self, mask):
    hot = np.zeros((mask.shape[0], mask.shape[1], self.n_class))
    hot[:, :, 1] = (mask[:, :, 1]==255).astype(int)
    hot[..., 0] = (mask[:, :, 1]==0).astype(int)
    return hot
```

This function converts the masks to one hot before they are loaded. I am using the provided ImageDataProvider class. Self.n_classes equals 2, but during training I am getting the error 'could not broadcast input array from shape (300,300,2) into shape (300,300).'

Thank you in advance.

**Comment by jakeret** [comment]
not sure where you use this function. The `ImageDataProvider` automatically creates a one-hot encoding if `n_classes==2`

**Comment by mfrohman123** [comment]
I figured it out; this function was used to convert the training labels to one-hot before being loaded in the ImageDataProvider class. Thanks!
