### ISSUE TITLE
util.py里的代码问题

### ISSUE THREAD

**Issue by zhulf0804** [jakeret/tf_unet#240]
如下代码段是否应该是if np.amax(img) != 0:

if np.argmax(img) != 0:
        img /= np.amax(img)

**Comment by jakeret** [comment]
what do you mean?

**Comment by zhulf0804** [comment]
I'm sorry to describe it in Chinese.

I mean, the 77th  line in the code file of https://github.com/jakeret/tf_unet/blob/master/tf_unet/util.py,
you may have a very little mistake.

And i find you have corrected it 9 hours ago.
