### ISSUE TITLE
Recommended way to change input and output size

### ISSUE THREAD

**Issue by I-CANT-CODE** [jakeret/tf_unet#242]
Hello,

I am attempting to train on 128*128 input and output images. What is the recommended way to modify the architecture to support this type of data?

Edit: forgot to specify, both the input and output are Black and white images.

**Comment by jakeret** [comment]
In principle you don't have to change anything in the network architecture. The implementation if capable of dealing with any sized image data

**Comment by I-CANT-CODE** [comment]
Oh awesome! Thanks.
