### ISSUE TITLE
Can not save prediction

### ISSUE THREAD

**Issue by I-CANT-CODE** [jakeret/tf_unet#246]
my code:

my code is as such:

prediction = net.predict(path/to/model, input_test)
util.save_image(prediction, "file.jpg")

I get a TypeError: Can't handle this data type

how can I save just the prediction image?

**Comment by jakeret** [comment]
the returned prediction is a 4d tensor. To save an image tf_unet relies on the Pillow package which expects an array that can be converted into an RGB image

**Comment by I-CANT-CODE** [comment]
are there any examples of how I can save it as an image that I can display?
