### ISSUE TITLE
A confusion in code about connection between downsample and upsample

### ISSUE THREAD

**Issue by ZJ1224** [jakeret/tf_unet#252]
I am new in the machine learning and sorry for my such easy problem. But I can't figure out how to deal deal with the connection between downsample and upsample in [for layer in range(layers - 2, -1, -1):](https://github.com/ZJ1224/tf_unet/blob/2cc5e588a70932a9dcced60f21c88664dc92a112/tf_unet/unet.py#L111).it seems that the code  jumps over the middle layer(the layer that conenects downsaple and upsample) in U-net.
I would appreciate very much if you would help me with that.

**Comment by jakeret** [comment]
Not sure if I understand your issue. The code tries to replicate the architecture of the original U-Net Ronneberger et al. paper. If you run the code you can use the graph visualisation of tensorboard to see the network layout

**Comment by ZJ1224** [comment]
> Not sure if I understand your issue. The code tries to replicate the architecture of the original U-Net Ronneberger et al. paper. If you run the code you can use the graph visualisation of tensorboard to see the network layout

thank you very much for your reply, I have figured it out!
