### ISSUE TITLE
ValueError: Cannot feed value of shape (4, 480, 480, 3) for Tensor 'y:0', which has shape '(?, ?, ?, 2)'

### ISSUE THREAD

**Issue by gzhengli** [jakeret/tf_unet#271]
**Describe the bug**
The train image of mine is 480*480*3,the src image and mask image in same.When training there is a error:
![image](https://user-images.githubusercontent.com/37538696/58925554-8d6cfa00-877a-11e9-9320-37b215cc82d1.png)
The train command is:
from tf_unet import unet,util,image_util
#preparing data loading
data_provider=image_util.ImageDataProvider("./train/*.jpg")
#setup & training
net=unet.Unet(layers=3,features_root=64,channels=3,n_class=2)
trainer=unet.Trainer(net)
path=trainer.train(data_provider,"./train-out",training_iters=32,epochs=100)
**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by gzhengli** [comment]
Find the problem：
The value of the n_class required by the network after loading the image is 3, which is 2 in my previous command.
Now I used the train command `net=unet.Unet(layers=3,features_root=64,channels=3,n_class=3)`.Training is normal.
But in my mask image I only label one type of target, the other is the background, why does the n_class need to be set to 3?

**Comment by obelling** [comment]
I have the same problem,can you tell me how to solve this?

**Comment by gzhengli** [comment]
> I have the same problem,can you tell me how to solve this?

You need to check the annotated images in your training data. The mask is best in grayscale.

**Comment by obelling** [comment]
@Gumballing 
While the annotated image is in grayscale(one channel),n_class is 2 ,I fear that training will has error like:
Cannot feed value of shape (4, 256, 256, 1) for Tensor 'y:0', which has shape '(?, ?, ?, 2)'

**Comment by obelling** [comment]
I had try convert the labels to gray and successfully train the model.Thank you very mach!

**Comment by Gumballing** [comment]
> I had try convert the labels to gray and successfully train the model.Thank you very mach!

no thank.
I have some problem in testing the model.If you tested success,I will need to consult your test code.
