### ISSUE TITLE
How to test？

### ISSUE THREAD

**Issue by Gumballing** [jakeret/tf_unet#274]
hi, jakeret

I have completed the training and got the result model.
I would like to use the following command to test, but how to properly load the test image into the required shape as data?
`prediction = net.predict(path, data)

unet.error_rate(prediction, util.crop_to_shape(label, prediction.shape))

img = util.combine_img_prediction(data, label, prediction)
util.save_image(img, "prediction.jpg")`

In the unet.py file, I see that the loaded data needs to be in the form of (n,nx,ny,channels) as shown in the figure below.  What is the value of n?
![image](https://user-images.githubusercontent.com/37538696/59159509-2b572080-8afd-11e9-8467-d734c1bfd32b.png)
Looking forward to your reply.

**Comment by jakeret** [comment]
Hi @gzhengli sorry for being so absent.

`n` is the number of images you feed into the network simultaneously but of course `n=1` is valid as well.

Best is to use the same `DataProvider` as you used for the training to ensure the exact same preprocessing of the test images

**Comment by gzhengli** [comment]
@jakeret thank you for your answer.
I use the default n of 1 to test, as shown in the following figure.
![image](https://user-images.githubusercontent.com/37538696/59415606-5e97f900-8df6-11e9-871c-cdc37ecb8d7b.png)
But the error was reported as follows:
![image](https://user-images.githubusercontent.com/37538696/59415800-c2222680-8df6-11e9-8cec-39351a58f698.png)
The image I used is RGB  three-channel. Is the command to load the image wrong?

**Comment by gzhengli** [comment]
@jakeret thank you~
Get it.
