### ISSUE TITLE
How to load custom dataset for training and validating?

### ISSUE THREAD

**Issue by panovr** [jakeret/tf_unet#35]
Hi,
  my own dataset directory structure is:
  ```
data
      |--<label1>
              |--<image001.jpg>
              |--<image001.png> (mask image for image001.jpg)
              |--<image002.jpg>
              |--<image002.png>
              |......
     |--<label2>
             |--<image001.jpg>
             |--<image001.png>
             |......
     |......
```
I also split the dataset into train and validating sets:
```
data
    |--train
          |--<label1>
                  |--<image001.jpg>
                  |--<image001.png>
                  |......
          |--<label2>
                  |--<image001.jpg>
                  |--<image001.png>
                  |......
          |......
    |--val
         |--<label1>
                 |--<image002.jpg>
                 |--<image002.png>
                 |......
         |--<label2>
                 |--<image002.jpg>
                 |--<image002.png>
                 |......
```

May I ask how to load this dataset for training and validating?

**Comment by jakeret** [comment]
I think you can use the [`tf_unet.image_util.ImageDataProvider`](https://tf-unet.readthedocs.io/en/latest/tf_unet.html#tf_unet.image_util.ImageDataProvider). Internally it uses `glob` to resolve the files. 
You need to pass a glob search pattern as `search_path` that fits your data structure.
To distingush the mask and the data you can use two `suffix` parameters.

**Comment by panovr** [comment]
It makes sense, thanks!

**Comment by mrtalkingbadger** [comment]
Hello, i have a few Questions for preparing my own dataset for tf_unet bacause i can`t find some example data in the net:

1. must the Training data all have the same size (or same size as the prediction_data) or can it be arbitrary?

Would be great if someone could give me a few hints About that!

**Comment by jakeret** [comment]
Yes the images should have the same format. Make sure to use an even number of pixels for x and y
