### ISSUE TITLE
Issue with groundtruth shape?

### ISSUE THREAD

**Issue by jeanpat** [jakeret/tf_unet#36]
Hi,
I met an issue regarding a tensor dimension:

`ValueError: Cannot feed value of shape (4, 80, 82, 2) for Tensor 'Placeholder_1:0', which has shape '(?, ?, ?, 4)'`

 The dataset consists in pairs of greyscale / groundtruth images, both images has a shape (80,82,1). The groundtruth contains pixels of value:

- 0:background
- 1,2 : objects
- 3 : pixels belonging to overlapping parts of the objects

The following code (modified from https://tf-unet.readthedocs.io/en/latest/usage.html) illustrates the nature of the data and the way the code fails:

[notebook on gist](https://gist.github.com/jeanpat/df407399def84d65fa3e1bb61a57c219)

Thanks for your advices.
JP

**Comment by jakeret** [comment]
This looks interessting. The error occurs, because the `ImageDataProvider` does not (yet) support multiclass input. 
You can add this by subclassing the `ImageDataProvider` class and adapting the `_next_data` method. I did that in one of the [examples](https://github.com/jakeret/tf_unet/blob/master/scripts/ufig_util.py#L74)

**Comment by jeanpat** [comment]
Thank's a lot, I'll try that.

**Comment by jeanpat** [comment]
I tried naively to see what's happen when using you modified _DataProvider()_ class as follow:

```
search = os.path.join('..','DeepFISH','dataset','LowRes','train','UnetData','*.tif')
#data_provider = image_util.ImageDataProvider(search)#, data_suffix= '.png', mask_suffix='_mask.png')
print(search)
## with new data provider

#suppose 4 labels, search :path to the images, a_min, a_max: 100 pairs of images?
data_provider = DataProvider(4, search,a_min=1, a_max=100)
```

Things went wrong as follow:


```
h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/tmp/pip-at6d2npe-build/h5py/_objects.c:2684)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/tmp/pip-at6d2npe-build/h5py/_objects.c:2642)()

h5py/h5f.pyx in h5py.h5f.open (/tmp/pip-at6d2npe-build/h5py/h5f.c:1930)()

OSError: Unable to open file (Unable to open file: name = '../deepfish/dataset/lowres/train/unetdata/*.tif', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
```
One can notice that the path was modified to lower case and I don't know how to modify the __next_data()_ function to handle a multiclass groundtruth image.

anyway,thank you for your work.

**Comment by jakeret** [comment]
While the DataProvider from the examples works with the HDF5 binary file format. 
From your listing I take that your data are `tif` images, which explains why it doesn't work. You can use the logic form the DataProvider but you have to adapt it a bit so that it can open tif files
