### ISSUE TITLE
unet.Unet class

### ISSUE THREAD

**Issue by roestigraben** [jakeret/tf_unet#44]
Hello,
I don't see any documentation for the parameters
"features_root" and "layers"

many thanks for updating
Peter

**Comment by jakeret** [comment]
You find it here: https://tf-unet.readthedocs.io/en/latest/tf_unet.html#tf_unet.unet.create_conv_net

**Comment by roestigraben** [comment]
I apologise for not seeing this!

Have a good weekend

Peter

**Comment by jakeret** [comment]
No worries. Hope it helps
