### ISSUE TITLE
Keras 2

### ISSUE THREAD

**Issue by hadim** [jakeret/tf_unet#45]
Hi and congrats for this promising project. Did you consider porting it to Keras 2 so people with little background in machine learning can easily understand and tweak your UNet implementation ?

Also Keras 2 will be supported for years and allow user to run their model on multiple backends such as Theano, Tensorflow, JavaScript, Scala, Java, etc). See here for more details : https://blog.keras.io/introducing-keras-2.html

That would be really nice !

**Comment by jakeret** [comment]
I'm a big fan of Keras and I already thought about implementing a UNet with it. 
I would probably not port the current `tf_unet` to Keras but rather reimplement a separate project.
