### ISSUE TITLE
how to save, restore and use the trained model?

### ISSUE THREAD

**Issue by bhralzz** [jakeret/tf_unet#49]
Dear all
Please give an example hot to save, load and use trained model in this code?
Thanks

**Comment by jakeret** [comment]
Hi, the model is automatically saved during training to this [folder](https://github.com/jakeret/tf_unet/blob/master/tf_unet/unet.py#L302).
The model itself provides a `save`, `restore` and `predict` method. See the [docs](https://tf-unet.readthedocs.io/en/latest/tf_unet.html#tf_unet.unet.Unet).

**Comment by Billsbob** [comment]
I'm trying to feed new images into a trained model and am struggling to understand how to do that (doesn't help that I am unfamiliar with python and learning as I go).  I understand that the tools are included in the code and I've tried to emulate the included Radio example and the toy example but I keep running into the issue of the image_util treating the new images like training data and hanging up on the fact that there are no _mask.tif files.  Deleting parts of the code or copying parts that seem relevant from image_util causes more problems.  One of my attempts below.

```
from tf_unet import image_util, unet, util
import glob

model_path = 'output/model.ckpt'
datapath = 'images/verification/*.tif'
files = glob.glob(datapath)

data_provider = image_util.ImageDataProvider(datapath, data_suffix = '.tif')
data_provider.channels = 3
data_provider.n_class = 2
net = unet.Unet(channels=3, n_class=2, layers=3, features_root=64)

data = data_provider(1)
prediction = unet.predict(model_path, data)

img = util.to_rgb(prediction[..., 1].reshape(-1, prediction.shape[2], 1))
util.save_image(img, "prediction.jpg")
```

The response is - E:\tf_unet>python testrun.py
Number of files used: 6
Number of channels: 1
Number of classes: 2
2019-01-23 21:08:42,420 Layers 3, features 64, filter size 3x3, pool size: 2x2
Traceback (most recent call last):
  File "testrun.py", line 13, in <module>
    data = data_provider(1)
  File "E:\tf_unet\tf_unet\image_util.py", line 77, in __call__
    train_data = self._load_data_and_label()
  File "E:\tf_unet\tf_unet\image_util.py", line 54, in _load_data_and_label
    return train_data.reshape(1, ny, nx, self.channels),
ValueError: cannot reshape array of size 8967000 into shape (1,2989,3000,3)

Hoping for any straightforward advice on how to call back the model and direct it to output predictions on novel data images.

**Comment by jakeret** [comment]
There are potentially many ways to do that. If you want to minimize your work you could simply change the `mask_suffix` of the `ImageDataProvider` to be ` = '.tif'`
