### ISSUE TITLE
Format of input?

### ISSUE THREAD

**Issue by sansinghsanjay** [jakeret/tf_unet#5]
I have a numpy (.npy) file having data of 564 image files, shape is [564, 420, 580] and same for their masks, [564, 420, 580].

I am saving these numpy objects in a h5py file and then passing it like:

```
dataset_file = h5py.File(source_path, 'r')
generator = Generator(1, dataset_file)
```

but getting following errors:
AttributeError: 'int' object has no attribute 'encode'
at line: 41 of radio_util.py:
`with h5py.File(self.files[self.file_idx], "r") as fp`

Please help me...

**Comment by sansinghsanjay** [comment]
I worked with different approaches and got answer of my question.

Here, we have to pass pair of image and its mask in h5 file. So, every pair of image and mask have an h5 file. We have to store all these h5 files in a directory and finally pass the path of this directory in Generator function.

**Comment by sansinghsanjay** [comment]
Can you please explain the format and shape in which input have to be passed in Generator function.
I have 564 images of shape [420, 580] and similarly 564 masks of shape [420, 580].

Currently I tried to pass these images and their masks in hdf5 files. So every pair of image and mask forms a hdf5 file with "data" for image and "mask" for mask. But still I am getting error: "Computed output size would be negative" at following line of store_prediction() function:

`prediction = sess.run(net.predicter, feed_dict={net.x: batch_x,net.y: batch_y,net.keep_prob: 1.})`

Thanks..

**Comment by jakeret** [comment]
Hi Sanjay Singh
The loading process is often very specific to the dataset. I therefore never anticipated that the `Generator` class is the scripts folder would be reused for another project.
I would recommend that you write your own loading code as it will give you the maximum flexiblity. Have a look at my implementations in the script folder or this examples that I wrote: https://gist.github.com/jakeret/cd1e8b51009b995c38b44101c38ad831

For a binary classification problem with gray scale images `tf_unet` expects the format

```python
data = np.zeros((n, nx, ny, 1))
mask = np.zeros((n, nx, ny, 2))
```

`n` is the `batch_size` and 1 because of the gray scale and 2 because of the one-hot encoding that is required.

Hope this helps

**Comment by ChelovekHe** [comment]
@sansinghsanjay I would recommend that you write your own loading code as it will give you the maximum flexiblity. like this:

import os,cv2,glob
import numpy as np


class Generator(object):
    channels = 1
    n_class = 2

    def __init__(self, files, a_min=0, a_max=255):
        self.train_path = os.path.join(files, 'train/'+'*.tif')
        self.num_for_read = 0
        self.a_min = a_min
        self.a_max = a_max
        self.names = []
        all_names = glob.glob(self.train_path)
        for image_name in all_names:
            if 'mask' in image_name:
                continue
            self.names.append([image_name])

        assert len(files) > 0, "No training files"
        print("Number of files used: %s" % len(files))

    def _next_data(self):
        image_name = self.names[self.num_for_read][0]
        label_name = image_name.split('.')[0] + '_mask.tif'

        img = np.squeeze(cv2.imread(image_name, cv2.IMREAD_GRAYSCALE))
        label = np.squeeze(cv2.imread(label_name, cv2.IMREAD_GRAYSCALE))

        return img,label

    def _load_data_and_label(self):
        data, label = self._next_data()
        self.num_for_read += 1
        nx = data.shape[1]
        ny = data.shape[0]

        # normalization
        data = np.clip(np.fabs(data), self.a_min, self.a_max)
        train_data = data.reshape(1,ny, nx, 1)
        train_data -= np.amin(data)
        train_data /= np.amax(data)
        labels = np.zeros((1,ny, nx, 2), dtype=np.float32)
        labels[..., 1] = label
        labels[..., 0] = ~label
        return train_data, labels

    def __call__(self, n):
        train_data, labels = self._load_data_and_label()
        nx = train_data.shape[1]
        ny = train_data.shape[2]

        X = np.zeros((n, nx, ny, 1))
        Y = np.zeros((n, nx, ny, 2))

        X[0] = train_data
        Y[0] = labels
        for i in range(0, n):
            train_data, labels = self._load_data_and_label()
            X[i] = train_data
            Y[i] = labels

        return X, Y

**Comment by sansinghsanjay** [comment]
Thanks a lot...
I am working with this package and get back to you if I faced any more issues..

Thanks..
