### ISSUE TITLE
tensorboard using

### ISSUE THREAD

**Issue by bhralzz** [jakeret/tf_unet#52]
How to use tensorboard in this code?

**Comment by AlibekJ** [comment]
It works out of the box. 
`tensorboard --logdir <YOUR train FOLDER>`

**Comment by bhralzz** [comment]
I have not used tensorboar ever, so please guide step by step how to visualize network structure and learning progress using it.
thanks

**Comment by jakeret** [comment]
As @AlibekJ  wrote it works out of the box. Tensorboard itself is fairly intuitive. Anyway there is plenty of [documentation](https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow/tensorboard/README.md) out there. Let me know if there is something that needs more clarification
