### ISSUE TITLE
is there any setting should be considered in using this code?

### ISSUE THREAD

**Issue by bhralzz** [jakeret/tf_unet#53]
Hi
I am using this code right now,
is there any setting that should be considered about using this code?
i.e. input pixel values range? ground-truth numbering?....?
I used this code
but the result is very bad and the code output is below 0.5 and should be considered as 0, at result 
whole of output shown black.
How I can optimize the result?
please please help!!!

**Comment by jakeret** [comment]
As for deep learning there is no one correct solution that work for all problems. A starting point I can recommend is `layers=3, features_root=64` and `epochs=100`.
Check the **Tensorboard**, ideally the training should have a similar behavoir as shown in the [usage section](https://tf-unet.readthedocs.io/en/latest/usage.html).
If you use the provided tools to load the data the values are automatically normalized to [0, 1). 
There is the option to automatically clip very large values, which is typically a good idea. 

If this does lead to reasonable results you might want to explore furhter normalization (zero-mean and unit variance).

Not sure what you mean with

> ground-truth numbering

**Comment by bhralzz** [comment]
Actually
I asked about format of groundtruth
For example l want to segment brain tumor
So output image should be in a tumor-nontumor format
Which is the number of classes?
And 
How I can code the GT images?

**Comment by jakeret** [comment]
Fascinating!
So, this sounds like a binary classification problem. Hence,the number of
classes is two.
As for the ground truth, it would be an image (or boolean array) where the
values are set to 1 if the pixel is a tumor and 0 if not.

**Comment by bhralzz** [comment]
Dear Joel 
Thanks for reply.
I test my code and the setting exactly is the same as you said.
I have about 30000 images which about 15000 of them have a small region segmented as tumor (1)
By running the code the error parameters sound good max 2 or 3 %
However when I go to test my code on test image (even train image) the output is black (full of zero)
my network generate output of full zero.
is there any problem?

**Comment by AlibekJ** [comment]
Hey @bhralzz, can you share your dataset? Would love to help.

**Comment by bhralzz** [comment]
Its very huge(about 16 GB)
But I can share a chunk of samples (300 image with their mask)
The images have 12 channels which first 4 channels are real and remains were derived from first four.
You can use first four channels if you want. Data in .mat format and you can find it in 

http://s8.picofile.com/d/8295851018/ea462ca7-d7fa-4a48-a3b1-3be34846f15a/tr.rar

Please consider best setting for the network
Thanks for your help.

**Comment by bhralzz** [comment]
Hi
Dear Jakeret and AlibekJ
Is there any solution?

**Comment by bhralzz** [comment]
Dear All,
Please give the download link of datasets used in demo examples!.
Thanks again

**Comment by bhralzz** [comment]
Any comment?

**Comment by jakeret** [comment]
Hi @bhralzz sorry for the late reply. Here is the demo on how to train the network on the RFI data set (https://github.com/jakeret/tf_unet/blob/master/demo/demo_radio_data.ipynb).

12 channels is fairly large to get startet. Have you experimented with a smaller number of channels and then gratually increasing the complexity?
