### ISSUE TITLE
usage help, training files

### ISSUE THREAD

**Issue by gopi77** [jakeret/tf_unet#57]
Hi 

I started as per this link, 
1. http://tf-unet.readthedocs.io/en/latest/installation.html
2. http://tf-unet.readthedocs.io/en/latest/usage.html.

Got error when at this python command, data_provider = image_util.ImageDataProvider("fishes/train/*.tif")
AssertionError: No training files

How to get these training files? any other link for prerequisites available?, Please help.

Regards
Gopi. J

**Comment by akashmaity** [comment]
What are the names of training and mask images of your dataset?

**Comment by gopi77** [comment]
Hi
I am looking for existing training files used during development. ( I don't have any from my side)

**Comment by akashmaity** [comment]
There is no existing dataset as far as I know. Download any dataset and try running.

**Comment by jakeret** [comment]
The package doesn't ship with any kind of data. There is a full [toy demo ](https://github.com/jakeret/tf_unet/blob/master/demo/demo_toy_problem.ipynb) and several [scripts](https://github.com/jakeret/tf_unet/tree/master/scripts) showing how to run the code.

It should be easy to use the toy demo to generate a data set if you want
