### ISSUE TITLE
batch_size can't be bigger than 1?

### ISSUE THREAD

**Issue by PiaoLiangHXD** [jakeret/tf_unet#61]
Hi, your default batch_size for training is 1 in line 305 of unet.py. This confuses me because I think a bigger batch_size is better (I usually use 64 as batch_size in image classification).
 Well I tested batch_size  2 or 3 or 5, and met "GPU out of memory" problem. So is it the reason why you use batch_size = 1? Or maybe there are other reasons that batch_size has to be 1? If batch_size could be bigger than 1, then is there any solutions to reduce parameter numbers to save GPU memory?
I'm new to this field, thank you so much about your sharing.
:)

**Comment by amejs** [comment]
Hello, the reason why the batch size is 1 is the size of the input (572x572), you could reduce the input size and increase the batch size. I would also recommend you to read the paper if you want to use this architecture https://arxiv.org/abs/1505.04597 They explain that to compensate for the small batch size, they use a high momentum (0.99), good luck!
Best regards, Amelia.

**Comment by PiaoLiangHXD** [comment]
"To minimize the overhead and make maximum use
of the GPU memory, we favor large input tiles over a large batch size and hence
reduce the batch to a single image. Accordingly we use a high momentum (0.99)
such that a large number of the previously"

@amejs  Yes I found it!! Thanks sooooooo much!
