### ISSUE TITLE
Segmenting RGB Images?

### ISSUE THREAD

**Issue by carsnwd** [jakeret/tf_unet#66]
I'm trying to use this to segment RGB images, however I keep getting an error saying I need to be in grayscale like such...

ValueError: could not broadcast input array from shape (300,500,3) into shape (300,500)

So I converted all my labeled images to grayscale and then it started to work, but during optimization crashes again with the same error.

Can I take an RGB image, have it labelled in grayscale, and then run it with this library or do I have to do something else? 

Thanks!

**Comment by jakeret** [comment]
Have you set the `channels` parameter to `3` for an RGB image?

The [simple example](https://github.com/jakeret/tf_unet/blob/master/scripts/launcher.py) is working on RGB images

**Comment by tottitt** [comment]
After I use ImageDataProvider to load RGB images (jpg format). When I want to check the shape of the loaded data, I have the same issue.  Could you show an example of loading RGB images?

The example was using a RgbDataProvider which is different than loading.

**Comment by calyun** [comment]
My issue is similar, when using the ImageDataProvider to load .png files.

**Comment by jakeret** [comment]
see #75
