### ISSUE TITLE
Cannot import tf_unet

### ISSUE THREAD

**Issue by changjianli** [jakeret/tf_unet#69]
Hi,

I am new to tensorflow and tf_unet, and I already install the tf_unet as the document says. But when I want to run the test in test folder, I got an error:

(C:\Dev\Anaconda3) D:\SketchCNN\tf_unet\test>python test_tf_unet.py
Traceback (most recent call last):
  File "test_tf_unet.py", line 10, in <module>
    from tf_unet import tf_unet
ImportError: cannot import name 'tf_unet'

How to solve it? Please help and thanks

**Comment by jakeret** [comment]
Your import seems incorrect. It should rather be something like:

```
from tf_unet import unet
from tf_unet import util
```
Check out the examples in the script folder

**Comment by changjianli** [comment]
Thanks and it now works.
