### ISSUE TITLE
multiclass mask

### ISSUE THREAD

**Issue by tottitt** [jakeret/tf_unet#72]
Hi, I m new here. 

Maybe a stupid question. Is there any example to let data loader load 3 class mask and how should we prepare the mask, single channel or multichannel, etc?

Does mask need to have same number of channels as input data?

**Comment by jakeret** [comment]
Hi there is an, admitetly, slightly convoluted [example](https://github.com/jakeret/tf_unet/blob/master/scripts/ufig_launcher.py).

The expected dimensions for mutliclass problems is:
data: `[batch_size, x, y, channels]`
mask: `[batch_size, x, y, classes]`
