### ISSUE TITLE
Ability to retrieve individual segments from the predicted image segmentation

### ISSUE THREAD

**Issue by inzamamul** [jakeret/tf_unet#73]
What is the procedure for saving individual segments (e.g. multiple different cells contained in same sized bounding boxes) from a predicted image segmentation of a cell plate (e.g. an image with many cells). 

using predict(self, model_path, x_test), I can get predict the segmentation, but I'm not too sure how to retrieve individual segments (cells in my case)

**Comment by jakeret** [comment]
After the segmentation one typically applies some thresholding on the class probabilities. Then you would run some kind of cluster detection algorithm. One packages that can be helpful for this is OpenCV

**Comment by inzamamul** [comment]
Ah I see. Excuse my ignorance, but is then tf_unet then a more sophisticated, more efficient version of this [this matlab example](https://uk.mathworks.com/help/images/examples/detecting-a-cell-using-image-segmentation.html) ?

**Comment by jakeret** [comment]
`tf_unet` can be trained to do the image segmentation. The later steps (dialate, erode, etc.) are not contained in the package. There are various python packages capable to do that efficiently
