### ISSUE TITLE
ValueError: could not broadcast input array from shape (200,200,3) into shape (200,200)

### ISSUE THREAD

**Issue by calyun** [jakeret/tf_unet#75]
All train inputs and labels are 200x200 RGB images. Channels is set to 3. image_util.py is unmodified (except for changing channels = 3).

The error is:
```
Traceback (most recent call last):
  File "run.py", line 41, in <module>
    dropout=0.5, display_step=10)
  File "D:\HAOYU\Unet\lab_unet\tf_unet\unet.py", line 389, in train
    test_x, test_y = data_provider(self.verification_batch_size)
  File "D:\HAOYU\Unet\lab_unet\tf_unet\image_util.py", line 87, in __call__
    train_data, labels = self._load_data_and_label()
  File "D:\HAOYU\Unet\lab_unet\tf_unet\image_util.py", line 50, in _load_data_and_label
    labels = self._process_labels(label)
  File "D:\HAOYU\Unet\lab_unet\tf_unet\image_util.py", line 64, in _process_labels
    labels[..., 1] = label
ValueError: could not broadcast input array from shape (200,200,3) into shape (200,200)
```

The relevant portion of my run.py is:

```
data_provider = image_util.ImageDataProvider(DATA_ROOT+"/train/*.png", data_suffix="_lowRes.png", mask_suffix="_highRes.png")

net = unet.Unet(layers=3,
	features_root=64
	channels=3,
	n_class=2,
	cost="l2") # I have changed some parameters for _get_cost(), shouldn't matter here

trainer = unet.Trainer(net, optimizer="adam")
path = OUTPUT_PATH

path = trainer.train(data_provider, path,
	training_iters=TRAIN_ITERS, epochs=EPOCHS,
	dropout=0.5, display_step=10)
```

**Comment by jakeret** [comment]
Looks like the implementation is making the assumption that the labels are binary. Can you try this:

` data_provider = image_util.ImageDataProvider(DATA_ROOT+"/train/*.png", data_suffix="_lowRes.png", mask_suffix="_highRes.png")`

`data_provider.n_class = 3`

**Comment by calyun** [comment]
Thanks!
Do you have any idea how I could modify the Unet to produce higher-resolution images given a high-resolution image as the ground truth (compared to its current usage as segmentation)? I am to do so for my lab, and I've been poking around the net the last few days and still trying to piece together how the output is produced.

**Comment by jakeret** [comment]
The lower resolution of the output is due to the network architecture. You can feed in a larger input by mirroring the borders of the input image. A neat way to do so was proposed here #41
