### ISSUE TITLE
what's the command seek

### ISSUE THREAD

**Issue by zhcf** [jakeret/tf_unet#77]
In the demo/demo_radio_data.ipynb,  the seek command is being used, but I can not find this command on  my Linux Server, what's the command, what package need be installed  for this command.

Thanks.

**Comment by jakeret** [comment]
HIDE&SEEK are two packages for the processing of radio astronomy data. You
find them here:
https://github.com/cosmo-ethz/seek
https://github.com/cosmo-ethz/hide

**Comment by zhcf** [comment]
Thank you, I will try

**Comment by zhcf** [comment]
Seek command must be run under the seek dir, otherwise we will get this error.
IOError: /usr/lib/python2.7/site-packages/seek-0.1.0-py2.7.egg/seek/data/gain_template_7m_FFT_phase_switch_ADU_K.dat not found.

Then the file dir in this command, we should use the absolute path
seek --file-prefix='/opt/test/bgs_example_data' --post-processing-prefix='/opt/test/bgs_example_data/seek_cache' --chi-1=20 --overwrite=True seek.config.process_survey_fft

**Comment by YJonmo** [comment]
Help please:

$ seek --file-prefix='/home/yaqub/Downloads/bgs_example_data' --post-processing-prefix='/home/yaqub/Downloads/bgs_example_data/seek_cache' --chi-1=20 --overwrite=True seek.config.process_survey_fft

Traceback (most recent call last):
  File "/usr/local/bin/seek", line 11, in <module>
    load_entry_point('seek==0.1.0', 'console_scripts', 'seek')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2691, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2322, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named 'ivy.cli.main'

**Comment by jakeret** [comment]
If you follow the installation instruction for seek you should automatically get the [ivy](https://github.com/cosmo-ethz/ivy) package as well.

**Comment by YJonmo** [comment]
Thank you

**Comment by YJonmo** [comment]
Now the problem is that the pkg-resources is referring to the python3 libraries, whereas this tf_unet is written in python2:

"/usr/local/lib/python3.5/dist-packages/pkg_resources/init.py" ...

**Comment by jakeret** [comment]
I looks like something is not quite right with your installation procedure. afaik, tf_unet runs under python 2 and 3
