### ISSUE TITLE
binary classification task problem

### ISSUE THREAD

**Issue by 541435721** [jakeret/tf_unet#78]
Thanks for sharing your project.
I have some problem ,i hope to get your help.
The doc shows that the label shape should be [n, X, Y, classes]. so the label shape must be [n, X, Y, 2], and the label is a one-hot encoding.i tried, but the net didn't run correctly. I find an answer you writed under another Issue that  tf_unet is expecting a boolean label array For a binary classification task. It works, but the shape is  [n ,X, Y] which doesn't match the description in the docs. When I do some predictions, i used error_rate(),it didn't work.

**Comment by jakeret** [comment]
The label shape has indeed to be `[n, X, Y, 2]`. If you make use of the tools to load images that the `tf_unet` provides it expects a binary mask, which is automatically turned into a one-hot encoded array

**Comment by 541435721** [comment]
Thanks. I have solved this problem just now.
And another problem.
I'm predicting a image with the size of  (512,512).I set the layers=3. But I got a smaller prediction map whose shape is (472,472). How can I get a prediction map that have the same size of the input.
When I set layers !=3,such as 4,5,or some other numbers, it trans well without any errs. But when  I do some prediction, I get an InvalidArgumentError. The detail of err messages are as follows.
> InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [3,3,256,128] rhs shape= [512]
	 [[Node: save/Assign_6 = Assign[T=DT_FLOAT, _class=["loc:@Variable_14"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](Variable_14, save/RestoreV2_6/_23)]]

**Comment by jakeret** [comment]
Great!
Regarding the size. This is expected behaviour. There is more information on this in the original paper. One way to get a prediction of the original size is to mirror the borders of the input image. Search older issues to find a good solution using `OpenCV`.

Not quite sure what this means. Can you provide the entire traceback?

**Comment by 541435721** [comment]
The second problem i mentioned  was solved by myself. I created the model with a wrong parameter when testing. 
Thanks a lot for your patience and help.

**Comment by jakeret** [comment]
Cool. Glad I could help
