### ISSUE TITLE
Segmentation for classes more than 2

### ISSUE THREAD

**Issue by dakshvar22** [jakeret/tf_unet#79]
Hi,

I want to apply U-nets for segmentation of images where number of classes are more than 2. in principle, this is possible with U-Nets but does this implementation support that?

I see two kinds of DataProvider : 

1) ImageDataProvider - I see that n_class has been hardcoded to 2 in this function which means the number of output segmented classes will be 2. Please correct me if am wrong.
2) SimpleDataProvider - I see here that I can use this function for arbitrary numpy arrays. Should I be using this one for multi class segmentation?

Is there an example to show how to use this library for multi class segmentation?

Thanks

**Comment by dakshvar22** [comment]
@jakeret Any updates on this?

**Comment by jakeret** [comment]
This is indeed possible with `tf_unet`. There is an, admitetly, slightly convoluted [example](https://github.com/jakeret/tf_unet/blob/master/scripts/ufig_launcher.py).

You're correct the implementation of `ImageDataProvider` is not optimal for this. Anyway you can do

```
provider = ImageDataProvider(...)
provider.n_class = 27
```

If your mask is not stored in a format that can be loaded with the `Pillow` package (used in `ImageDataProvider`) you should rather use the `SimpleDataProvider` or write your own

**Comment by dakshvar22** [comment]
@jakeret Thank you for the reply.

I prefer using SimpleDataProvider and loading my own numpy arrays into it.
Just confirming my steps - 
1) Prepare RGB input images and the corresponding mask images. The number of channels in the mask images will correspond to the number of classes I want to segment. So, if I have 4 classes then my mask image will be of this dimension - [nx,ny,4]
2) Load these as numpy arrays and provide them to SimpleDataProvider.

Can you confirm if the above steps would work good?

I know this is off topic, but a small(yet very helpful) question. Are you aware of some open source tools which can help in creating such masked images for multiple classes?
Any help would be appreciated.

Thanks,
Daksh

**Comment by jakeret** [comment]
Sounds good!

Nope, sorry I don't. But I know that this is done quite frequently on bio medical images. Maybe that helps when searching

**Comment by dakshvar22** [comment]
Hi, I tried using Simple Data Provider - 

My numpy matrices are of the following dimension - 

Input - images_x - (161, 180, 248, 3)
Masked GT - images_y - (161, 180, 248, 2)

I use the generator as - 

`generator = image_util.SimpleDataProvider(images_x, images_y,channels=3,n_class=2)`

Unet instantiation - 

`net = unet.Unet(channels=generator.channels, n_class=generator.n_class, layers=5, features_root=64)`

Trainer - 

`trainer = unet.Trainer(net, optimizer="adam", opt_kwargs=dict(learning_rate=0.003))
`

When I execute the actual training step - 

`trainer.train(generator, "./trained_adam_noNorm_l5_f64_lr0.003", training_iters=32, epochs=50, display_step=5,write_graph=True)`

I get this error - 

> ValueErrorTraceback (most recent call last)
> <ipython-input-49-acccf11b3fe4> in <module>()
> ----> 1 path = trainer.train(generator, "./trained_adam_noNorm_l5_f64_lr0.003", training_iters=32, epochs=50, display_step=5,write_graph=True)
> 
> /home/jupyter/.local/lib/python2.7/site-packages/tf_unet-0.1.0-py2.7.egg/tf_unet/unet.pyc in train(self, data_provider, output_path, training_iters, epochs, dropout, display_step, restore, write_graph)
>     402                     self.net.restore(sess, ckpt.model_checkpoint_path)
>     403 
> --> 404             test_x, test_y = data_provider(self.verification_batch_size)
>     405             pred_shape = self.store_prediction(sess, test_x, test_y, "_init")
>     406 
> 
> /home/jupyter/.local/lib/python2.7/site-packages/tf_unet-0.1.0-py2.7.egg/tf_unet/image_util.pyc in __call__(self, n)
>      85 
>      86     def __call__(self, n):
> ---> 87         train_data, labels = self._load_data_and_label()
>      88         nx = train_data.shape[1]
>      89         ny = train_data.shape[2]
> 
> /home/jupyter/.local/lib/python2.7/site-packages/tf_unet-0.1.0-py2.7.egg/tf_unet/image_util.pyc in _load_data_and_label(self)
>      48 
>      49         train_data = self._process_data(data)
> ---> 50         labels = self._process_labels(label)
>      51 
>      52         train_data, labels = self._post_process(train_data, labels)
> 
> /home/jupyter/.local/lib/python2.7/site-packages/tf_unet-0.1.0-py2.7.egg/tf_unet/image_util.pyc in _process_labels(self, label)
>      62             ny = label.shape[0]
>      63             labels = np.zeros((ny, nx, self.n_class), dtype=np.float32)
> ---> 64             labels[..., 1] = label
>      65             labels[..., 0] = ~label
>      66             return labels
> 
> ValueError: could not broadcast input array from shape (180,248,2) into shape (180,248)

What could be going wrong?

**Comment by jakeret** [comment]
Could you try to feed in 
Masked GT - ` (161, 180, 248)` 

i.e. just one of the boolean values

**Comment by dakshvar22** [comment]
I commented out the call to the function - _process_labels() in image_utils.py file. I am guessing that is just needed for binary segmentation. Is that right? I am more concerned with multi-class segmentation, for which I think that function should not be called.
Please correct me if am wrong.
