### ISSUE TITLE
conv3d missing

### ISSUE THREAD

**Issue by 541435721** [jakeret/tf_unet#82]
I'm trying to implement 3D-Unet, and find the (project)[https://github.com/shiba24/3d-unet/blob/master/tensorflow/model.py] in github. But the functions of conv3d and deconv3d are missing. did you delete them?

**Comment by jakeret** [comment]
You can check the history [here](https://github.com/jakeret/tf_unet/commits/master/tf_unet/layers.py). Those function were not part of this repository. 
Maybe they were added by the other dev on the fork
