### ISSUE TITLE
How to train rgb image??

### ISSUE THREAD

**Issue by liuzhisheng1226** [jakeret/tf_unet#96]
I train my own images with following code,The image  size is (256,256,3),And the mask is Gray Scale Image(256,256),But its throw an error:
   data_provider=image_util.ImageDataProvider("/home/liuzhisheng/DATA/1/*.jpg")
    net=unet.Unet(layers=3,features_root=64,channels=3,n_class=2)
    trainer = unet.Trainer(net, optimizer="momentum", opt_kwargs=dict(momentum=0.2))
    path = trainer.train(data_provider, "./unet_trained", training_iters=20, epochs=10, display_step=2)

         62             ny = label.shape[0]
     63             labels = np.zeros((ny, nx, self.n_class), dtype=np.float32)
---> 64             labels[..., 1] = label
     65             labels[..., 0] = ~label
     66             return labels
ValueError: could not broadcast input array from shape (256,256,3) into shape (256,256)
My image:
![3616_130816](https://user-images.githubusercontent.com/19258612/30313573-5f77df66-97d0-11e7-86d1-2b2de02775e9.jpg)
![3616_130816_mask](https://user-images.githubusercontent.com/19258612/30313578-63c3db2e-97d0-11e7-9aae-dc992ebcd128.jpg)

**Comment by liuzhisheng1226** [comment]
This is my datasets:
![3584_130848_mask](https://user-images.githubusercontent.com/19258612/30312912-0e7d9256-97ce-11e7-969b-6153d8e041c9.jpg)
``
![4704_130752](https://user-images.githubusercontent.com/19258612/30312906-09f4f328-97ce-11e7-8747-2bd4347c6746.jpg)

**Comment by jakeret** [comment]
there is a slight issue with the `ImageDataProvider` as it assumes 2 classes by default. you do:

```
data_provider=image_util.ImageDataProvider("/home/liuzhisheng/DATA/1/*.jpg")
data_provider.n_class = 27
```

**Comment by liuzhisheng1226** [comment]
Thanks!
But my datasets has 2 classes,And my code is(n_class=2) :
data_provider=image_util.ImageDataProvider("/home/liuzhisheng/DATA/1/*.jpg")
net=unet.Unet(layers=3,features_root=64,channels=3,n_class=2)

**Comment by jakeret** [comment]
Ah I see. However the error `shape (256,256,3)` seems to indicate that you have 3 channels in the mask and not one (binary)

**Comment by liuzhisheng1226** [comment]
Thanks a lot,I train my own datasets,But it always display: 
2017-09-15 11:32:44,070 Iter 10, Minibatch Loss= 0.0005, Training Accuracy= 1.0000, Minibatch error= 0.0%
My code is following ,My datasets is the following image,And I don't where is the problem?

 def train(data_root,output_path,layers,features_root,channels,n_class,training_iters,epochs,display_step):
    data_provider=image_util.ImageDataProvider(data_root,data_suffix=".tif",mask_suffix="mask.tif")
    net=unet.Unet(layers=layers,features_root=features_root,channels=channels,n_class=n_class)
    trainer=unet.Trainer(net,optimizer="momentum",opt_kwargs=dict(momentum=0.2))  
 path=trainer.train(data_provider,output_path,training_iters=training_iters,epochs=epochs,display_step=display_step)
    x_test,y_test=data_provider(1)
    prediction=net.predict(path,x_test)
    print("Testing error rate:.2f%".format(unet.error_rate(prediction,util.crop_to_shape(y_test,prediction.shape))))

if __name__ == '__main__':
    train(data_root="/home/liuzhisheng/DATA/train_data/*.tif",output_path="./unet_trained",
          layers=3,features_root=64,channels=3,n_class=2,
          training_iters=10,epochs=10,display_step=2)

![tumor12736_152528](https://user-images.githubusercontent.com/19258612/30465629-a0a3fd08-9a0a-11e7-9c62-dd53b6f34d17.jpg)
![tumor12736_152528mask](https://user-images.githubusercontent.com/19258612/30465642-b0ad44de-9a0a-11e7-997e-50c96a6c69b4.jpg)

**Comment by jakeret** [comment]
As far as I could decipher the code looks ok. Maybe there is something not working as expected when loading your data set. I would recommend to check in a jupyter notebook what your `data_provider` is outputting and check if it in the correct format

**Comment by liuzhisheng1226** [comment]
Thanks a lot

**Comment by myway0101** [comment]
@liuzhisheng1226  
Hi, 

Any progress on your results? 

Please share your experience.

I try to use RGB color image for training. But, result is not good.
